### ISSUE TITLE
corrigir erro no plugin custom_forms ao exportar arquivo csv

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#11]
ver comentário https://github.com/IBICT/noosfero/issues/7#issuecomment-344000514 da issue #7 para mais detalhes.

**Comment by joenio** [comment]
Merge Request feito: https://gitlab.com/noosfero/noosfero/merge_requests/1389

Aguardando aprovação dos commiters do Noosfero.

**Comment by mnt-c** [comment]
Aprovado o merge request com a solução: https://gitlab.com/noosfero/noosfero/commit/3f0f20aa6d32b9490ae05375d048049aab474064.

O problema foi resolvido através da instalação local, identificando a origem do problema que havia no plugin e aplicando a solução devida juntamente com seus testes unitários e funcionais. Feito as correções foi enviado ao repositório oficial ( https://gitlab.com/noosfero/noosfero ) e aprovado pela equipe responsável.
