### ISSUE TITLE
alinhar campos do formulário gerado pelo plugin custom_form

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#12]
os campos do formulário do plugin custom_form estão desalinhadis, ver imagem em https://github.com/IBICT/noosfero/issues/7#issuecomment-344000514, corrigir o alinhamento e manter os campos com alinhamento correto.

**Comment by maxbborges** [comment]
Na realidade, a parte com problema de alinhamento é essa: https://github.com/IBICT/noosfero/issues/7#issuecomment-343998697

**Comment by maxbborges** [comment]
No tema padrão do noosfero o problema não é apresentado, em todas as formas de lista:
![captura de tela de 2018-01-24 13-47-43](https://user-images.githubusercontent.com/18174772/35341720-7b7a017a-010d-11e8-8983-cf5a0d4c1763.png)

**Comment by maxbborges** [comment]
Foi constatado que o problema era aparente somente no tema do Juventude, para a correção foi editando o arquivo style.css na pasta public/designs/themes/juventude, inserindo a seguinte linha de CSS entre as linhas 1408 e 1410:

#custom-forms-plugin_submission .formfieldline input[type="radio"], .formfieldline input[type="checkbox"] {
    width: 5%;
}

#custom-forms-plugin_submission .formfieldline label {
    display: inline-block;
    width: 90%;
}

a nova pagina ficará da seguinte forma:
![captura de tela de 2018-01-31 16-24-36](https://user-images.githubusercontent.com/18174772/35640233-bc3abf9c-06a3-11e8-8641-d7383344c858.png)

Corrigindo o problema dos campos estarem desalinhados.

**Comment by maxbborges** [comment]
Foi feito o merge-request das correções no link:
https://gitlab.com/noosfero-themes/juventude/merge_requests/2

O problema foi corrigido e a issue será fechada.
