### ISSUE TITLE
Erro nas imagens do formulario

### ISSUE THREAD

**Issue by maxbborges** [IBICT/noosfero#13]
Corrigir erro na visualizaçao/apresentação da imagem upada na criação de um novo formulario. Onde ao exibir a imagem na pagina não é a imagem selecionada e sim uma imagem com erro.

**Comment by maxbborges** [comment]
É possivel inserir uma nova imagem na criação de um novo formulario:
![captura de tela de 2018-01-24 13-29-34](https://user-images.githubusercontent.com/18174772/35340672-e0e6f278-010a-11e8-8c68-0ea885a5b75a.png)

entretando, essa imagem não possui nenhuma utilidade. Quando é apresentado o formulario pronto para resposta, a imagem não é apresentada em nenhum lugar:

![captura de tela de 2018-01-24 13-34-23](https://user-images.githubusercontent.com/18174772/35340824-566c55f6-010b-11e8-8f86-b8e8cfe944be.png)

**Comment by joenio** [comment]
@maxbborges essa imagem dá algum erro ou apenas não é exibida? você fez alguma correção relacionada a isso já, como está o andamento disso?

**Comment by maxbborges** [comment]
@joenio, a imagem somente vai para a galeria da comunidade, não sendo exibido e não havendo nenhum local destinado a imagem quando é aberto o formulario que foi criado com imagem.

Essa é a tela que é exibida ao abrir um formulario que foi criado com imagem. Pode-se notar que não há nenhuma imagem na tela, além da imagem da comunidade.
![captura de tela de 2018-01-31 16-24-36](https://user-images.githubusercontent.com/18174772/35640677-fb4f5ade-06a4-11e8-8224-b7c4877a59d1.png)

**Comment by maxbborges** [comment]
Como não é apresentado nenhum erro upar ou apresentar a imagem, a issue será fechada.
