### ISSUE TITLE
criar relatório de acessos ao portal da juventude

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#14]
1. acessar o awstats do portal da juventude: http://weblog.presidencia.gov.br/awstats/awstats.pl?config=www.juventude.gov.br
1. exportar os dados em arquivo pdf, imagem, etc (escolher o formato que desejar) do período de janeiro até hoje
1. enviar os dados para jaqueline

**Comment by joenio** [comment]
@FabioDsg testou o acesso da rede da SNJ e confirmou que é possível acessar o awstats diretamente de lá, então não será preciso exportar os dados, basta passar para jaqueline as informações de como acessar o awstats.

**Comment by mnt-c** [comment]
Entrei em contato com a jaqueline e acompanhei junto com ela alguns dos relatórios.

**Comment by FabioDsg** [comment]
Acredito que esta Issue pode ser fechada considerando que o proposto foi cumprido. Aguardando um ok do @caiomnt  e/ou @joenio.

**Comment by mnt-c** [comment]
Acredito também que o objetivo foi atingido, pois a Jaqueline confirmou que recebeu as informações do Fabio e mesma consegue acessar o awstats do portal, vou fechar a issue então no caso.
