### ISSUE TITLE
erro ao aceitar convite para entrar em comunidade secreta

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#16]
ao aceitar uma pessoa como membro de uma comunidade secreta ta dando erro de "community não pode ter integrantes"

solicitar detalhes do erro com Nayanne/DITEC

**Comment by luucilia** [comment]
Eu criei uma comunidade secreta e convidei pessoas para participarem, aparece que os amigos foram adicionados, mas eles não recebem nenhuma solicitação e ninguém é, realmente, adicionado na comunidade.

Tela:
![friend_added](https://user-images.githubusercontent.com/17516861/33718331-2235280e-db44-11e7-824d-05749dab18f0.png)

**Comment by FabioDsg** [comment]
Foram realizados testes e ao tentar aceitar um convite para participar de uma comunidade secreta o seguinte erro é mostrado:

![img-7056](https://user-images.githubusercontent.com/8026759/35807618-6949caf6-0a6a-11e8-8c5e-90990e4e418b.jpg)

Foi constatado que o convite só funciona via e-mail, ao tentar realizar um convite via nome de usuário, nenhuma notificação para ambas as partes é mostrada.

**Comment by luucilia** [comment]
Testei a funcionalidade da comunidade secreta na versão atual do noosfero.

Segue o passo-a-passo:

1. Ao convidar um usuário para entrar na comunidade aparece a seguinte notificação para o usuário:

![convite_com_secreta](https://user-images.githubusercontent.com/17516861/35859511-81235918-0b27-11e8-852c-d1355f4c266e.png)

2. Após aceitar o convite, o usuário que realizou o convite recebe uma notificação para aceitar e definir quais serão os papéis do novo integrante, como mostra a imagem:

![convite_com2](https://user-images.githubusercontent.com/17516861/35859585-da797a56-0b27-11e8-83e8-c92dba7c71ca.png)

3. Depois que o novo membro é aceito, a comunidade secreta não aparece em suas comunidades, exatamente por ser secreta, mas é possível acessá-la através da opção **Rede** no profile do usuário, como segue:

![convite3](https://user-images.githubusercontent.com/17516861/35859686-2f1b4ce2-0b28-11e8-9e7d-b3c9b18f651b.png)

Logo, este erro já foi corrigido na nova versão do noosfero.
