### ISSUE TITLE
Erro ao clicar no botão ativar/desativar comentários

### ISSUE THREAD

**Issue by FabioDsg** [IBICT/noosfero#17]
Ao clicar no botão ativar/desativar comentários do formulário http://juventude.gov.br/startups/consulta-plano-nacional-de-desenvolvimento/etapa-1/diagnostico-do-ecossistema-empreendedor#.WfoAM9WnEdU
é gerado um código html extra e o mesmo espirra na tela como visto nas imagens abaixo:

![bugplugincomment_02](https://user-images.githubusercontent.com/8026759/33073184-392a9032-cea9-11e7-8b09-a54eb9188b3a.PNG)

![bugplugincomment](https://user-images.githubusercontent.com/8026759/33073210-49db2e5a-cea9-11e7-8c5b-b58d9fe9d287.PNG)

O botão em questão:

![bugbotaoativarcomment](https://user-images.githubusercontent.com/8026759/33073219-5aaedf92-cea9-11e7-9830-4aac0ed5fe81.PNG)

Código extra gerado e espirrado na tela:

![codigoextra](https://user-images.githubusercontent.com/8026759/33074177-58ee17ba-ceac-11e7-99ec-7947a6cb1c82.PNG)

![macroadd](https://user-images.githubusercontent.com/8026759/33074183-5eddd76e-ceac-11e7-9fbc-2b3b592f2a80.PNG)

O problema foi corrigido de forma "parcial" removendo o código extra gerado ao clicar no botão ativar/desativar comentários porém, a origem do problema ainda está sendo investigada. Tal botão indica não estar funcional e quando o mesmo for clicado acontecerá novamente.

Segue o código original e funcional no momento:

[codigo_funcional.txt](https://github.com/IBICT/noosfero/files/1491414/codigo_funcional.txt)

**Comment by mnt-c** [comment]
Nas versões atuais do noosfero parece que já havia sido resolvido o vazamento. Acredito que a correção foi a partir desse commit: https://github.com/noosfero/noosfero/commit/4e618c2c293a34e819ca81cfb53ccd64f71f6521

Realizei um teste com o plugin e não ocorreu o erro no texto:

![comment](https://user-images.githubusercontent.com/18350825/33179475-b17b6630-d050-11e7-84d2-39b5f005fe9a.png)

![comment2](https://user-images.githubusercontent.com/18350825/33179498-c0be6dfe-d050-11e7-9102-49065a6a9bf4.png)

**Comment by caiomnt** [comment]
Arquivado para a atualização do servidor na Issue https://github.com/IBICT/noosfero/issues/20
