### ISSUE TITLE
criar consulta publica do Plano Nacional De Juventude

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#19]
* usar o mesmo modelo da consulta pública do plano de Startups, porem BEM mais simplificado
* serão 11 eixos (ou seja, 11 paginas com conteudo, e um campo de formulario)

**Comment by FabioDsg** [comment]
Acredito que esta seja uma possível solução. Segue um exemplo de como ficaria a consulta utilizando a opção "Embed". O documento pode ser rolado e lido por completo enquanto a opção comentar e os comentários já realizados permanecem fixos na página.

![pdf-works](https://user-images.githubusercontent.com/8026759/33175143-d41f1d58-d041-11e7-98e1-84228851362e.PNG)

O link se encontra no perfil do Maxwell e está como privado, assim sendo precisa estar logado para visualizar.

http://juventude.gov.br/max15/consulta-publica

Segue o código utilizado:

[Embed_Code.txt](https://github.com/IBICT/noosfero/files/1499329/Embed_Code.txt)

**Comment by maxbborges** [comment]
O Embed_Code.txt colocado pelo @FabioDsg foi testado e também funciona para links do SlideShare e Issuu, servindo não só para arquivos simplismente PDF.

**Comment by FabioDsg** [comment]
Na data de ontem 27/11/2017 foi feito o upload dos arquivos PDF para o seguinte diretório:
http://juventude.gov.br/plano-nacional-de-juventude/arquivos/consulta-publica

Foi criado um protótipo inicial composto pelas telas com PDF's embutidos e uma página inicial em branco.

O @maxbborges e @caiomnt concluíram realizando todos os ajustes necessários como, adicionar os textos, banner(s) e ajuste fino que caso queiram, tais atividades podem vir a ser detalhadas aqui. 

O resultado final e funcional se encontra no seguinte endereço.
http://juventude.gov.br/plano-nacional-de-juventude

**Comment by FabioDsg** [comment]
Foi constatado um problema em relação a visualização dos arquivos em pdf em dispositivos móveis, nos dispositivos IOS tal arquivo é visto como uma "imagem" e não permite a visualização de forma correta. Foram realizados testes em um dispositivo Android utilizando o Chrome mobile o download do PDF foi realizado de forma automática. 

Tal problema está sendo verificado.

**Comment by FabioDsg** [comment]
Foi realizada uma tentativa de substituição do código com a finalidade de teste, porém, o firewall bloqueia tal código.

![bloqueiofirewall](https://user-images.githubusercontent.com/8026759/33317961-0a6280f8-d420-11e7-91e5-fb5a6154781f.PNG)

Código em questão:

<object data="http://juventude.gov.br/articles/participatorio/0021/2406/1-PNJ-EIXO-1.pdf" type="application/pdf" 

width="100%" height="100%">
  <p>Your web browser doesn't have a PDF plugin.
  Instead you can <a href="http://juventude.gov.br/articles/participatorio/0021/2406/1-PNJ-EIXO-1.pdf">click here to
  download the PDF file.</a></p>
</object>

**Comment by FabioDsg** [comment]
Novamente o firewall bloqueia outro código. Este tem como proposta apresentar o PDF pelo google docs mantendo a ideia do "embed". 

![bloqueiofirewall_2](https://user-images.githubusercontent.com/8026759/33318566-2d068c6a-d422-11e7-9806-066875479c52.PNG)

Segue o código em questão:

`<object width="900" height="900" data="https://docs.google.com/gview?

embedded=true&url=http://juventude.gov.br/articles/participatorio/0021/2406/1-PNJ-EIXO-1.pdf"></object>`

**Comment by FabioDsg** [comment]
Após várias tentativas, o problema citado acima foi contornado utilizando o código para visualização do arquivo PDF via Google Docs inserido dentro do Iframe como no código abaixo:

`<iframe src="https://docs.google.com/gview?url=http://juventude.gov.br/articles/participatorio/0021/2412/7-PNJ-EIXO-7.pdf&embedded=true" width="760px" height="500px">
</iframe>`


Segue um print do funcionamento em dispositivo mobile IOS:

![804728805_59729](https://user-images.githubusercontent.com/8026759/33322844-ba2b993c-d431-11e7-9424-fc683d1e2c21.jpg)

**Comment by FabioDsg** [comment]
Segue um print do funcionamento em dispositivo Android:

![capture _2017-11-28-11-55-00](https://user-images.githubusercontent.com/8026759/33324058-8c2fff60-d435-11e7-87fa-2e6751b656a9.png)

**Comment by joenio** [comment]
muito bom @luciliapo @maxbborges @caiomnt @FabioDsg, valeu, bom trabalho!

**Comment by FabioDsg** [comment]
Todos os códigos foram atualizados. Pode ocorrer de uma mensagem "no preview available", ainda não foi investigado porém, acredita-se que seja por conta de uma lentidão na rede em determinado horário, e como os documentos estão armazenados no mesmo servidor acabam sendo afetados. 

Esta issue estará no aguardo da confirmação do funcionamento correto por parte do Michell e interessados.

**Comment by maxbborges** [comment]
É possível que exista um bloqueio no firewall quando se coloca a pré-visualização do google, como o problema descrito na https://github.com/IBICT/noosfero/issues/19#issuecomment-347537348 ocorria ocasionalmente foi colocado os arquivos PDFs em outro servidor, para testes no Google Drive pessoal e então, com os links do drive e com a pre-visualização do google foi constatado que o problema não ocorria. É necessário colocar esses PDFs no drive da SNJ e alterar os links.

**Comment by mnt-c** [comment]
Foi incluído no portal o banner de acesso a consulta tanto na página principal, quanto nas barras lateral de banners solicitado pelo Michell.

**Banner na página inicial** 

![image](https://user-images.githubusercontent.com/18350825/33440246-a6a0adc0-d5d6-11e7-88ea-d50c593a9db5.png)


**Banner na página lateral** 

![image](https://user-images.githubusercontent.com/18350825/33440328-d7806458-d5d6-11e7-9056-d85ae4ff6db7.png)
