### ISSUE TITLE
página de categoria com vazamento de HTML

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#2]
* no final da página clicar em "Educação"
* ver print em anexo

![captura de tela de 2017-11-06 11-56-53](https://user-images.githubusercontent.com/44172/32444403-aa08cb46-c2e9-11e7-81ab-5132398c0ce0.png)

* proposta de soluçao, ver commit 397b89a17c1d2515de9854f68cdabfe5e0e6acb2

**Comment by maxbborges** [comment]
O bug já foi resolvido no commit 2ddfa076a5
