### ISSUE TITLE
atualizar servidor de produção do juventude.gov.br

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#20]
o upstream do noosfero está bem mais atualizado que a atual versão em produção, vários bugs corrigidos e melhorias implementadas.

**Comment by joenio** [comment]
issue relacionada: #2

**Comment by mnt-c** [comment]
issue relacionada: https://github.com/IBICT/noosfero/issues/17

**Comment by joenio** [comment]
eu e o leandro nunes (serpro) iniciamos a atualização dos servidores do participa/juventude, a presidência trouxe ele de salvador para ajudar nesta atividade, hoje quarta dia 31 de janeiro será feito a migração do portal participa.br e na sequência será feito atualização do juventude também.

**Comment by joenio** [comment]
Leandro Nunes (SERPRO) passou os dias 29, 30 e 31 de janeiro dando apoio nos problemas do ambiente Nossfero do Participa visando atualização de produção, ao final o servidor não foi atualizado e ficou um novo planejamento de atualizar após o carnaval.

A atualização do Juventude será feita após a atualização do Participa pois a equipe que mantém os servidores irá utilizar o aprendizado e soluções adotadas no Participa para realizar o deploy/update do portal Juventude.

* Previsão de atualização do participa: 19/02
* Previsão de atualização do juventude: 19/02 + 1 semana = 26/02
