### ISSUE TITLE
Permitir a organização de imagens por álbuns

### ISSUE THREAD

**Issue by luucilia** [IBICT/noosfero#23]
Permitir que as imagens possam ser organizadas por álbuns.

Verificar se é para a Página Imagens e/ou a Galeria de Imagens.

**Comment by mnt-c** [comment]
Dentro da ferramenta do Noosfero tem como adicionar álbuns de imagens. Editando o perfil desejado do blog nas opções de gerenciamento de conteúdo, possui um botão de novo conteúdo e no mesmo tem a opção de galeria:

![image](https://user-images.githubusercontent.com/18350825/33444327-1f0b9ae0-d5e1-11e7-9642-b710f7a3efc0.png)

Para incluir uma imagem no álbum, terá que realizar o upload da imagem desejada em conteúdos e escolher o caminho do álbum criado.

Conversado com uma das solicitantes e a solução encontrada atende a demanda.
