### ISSUE TITLE
Verificar a existência de dois sistemas na página publicações

### ISSUE THREAD

**Issue by luucilia** [IBICT/noosfero#25]
Verificar porque existem dois sistemas, duplicando as mesmas informações: ISSUU e BIBLIOTECA.

**Comment by FabioDsg** [comment]
Em um primeiro contato foi verificado que o uso do ISSUU e BIBLIOTECA tem propostas diferentes. Um sistema tem como finalidade apresentar o conteúdo de uma forma mais elegante e agradável, o outro apesar de também apresentar, está sendo visto como uma forma de manter uma cópia arquivada para futuras consultas.
 No caso do ISSUU ao clicar no link disponível, o usuário é redirecionado automaticamente para o conteúdo já disponível e pronto para leitura, já na biblioteca, o usuário precisa acessá-la, entrar com a busca do arquivo, localizá-lo, solicitar que ele seja aberto ou selecionar a opção de salvar para visualizar posteriormente.

**Comment by joenio** [comment]
@FabioDsg mas é necessário explicar ao pessoal da SNJ que não faz sentido ter dois sistemas fazendo a mesma coisa, além de duplicar esforço isso pode gerar inconsistência nos dados, uma vez que há duplicação de informação.

É necesssário saber se o ISSUU é realmente inprescindível e porque é inprenscindível, quais features do ISSUU a Secretaria não pode viver sem? Mesmo sendo um sistema mais elegante há de fato algum requisito fundamental que justifique o seu uso? O ideal é migrar o uso que hoje é feito via ISSUU para a BIBLIOTECA e manter apenas a BIBLIOTECA.

**Comment by FabioDsg** [comment]
Já estou alinhando com Michell, ele informou que se fosse necessário poderia substituir o ISSUU. Estamos apenas acertando os detalhes e assim que ele sinalizar e a instrução for passada essa issue será fechada.

**Comment by FabioDsg** [comment]
Foi feito o contato com a Estela, ela sugeriu uma pequena reunião, incluindo o Diego e as meninas da biblioteca para decidir a melhor solução, uma vez que segundo ela, a biblioteca precisaria passar por algumas mudanças ou permitir que o conteúdo em destaque fosse disponibilizado de forma semelhante ao ISSUU.

**Comment by joenio** [comment]
Vejo que a SNJ está hoje dependente do ISSUU, creio que não justifica consumir horas de reunião de tanta gente pra isso, vamos abortar essa missão por enquanto e deixar a Secretaria usando em duplicidade os dois sistemas.
