### ISSUE TITLE
Bloqueios do Firewall

### ISSUE THREAD

**Issue by maxbborges** [IBICT/noosfero#27]
Registros de todos os possíveis bloqueios que ocorreram durante a tentativa de alteração no site juventude.gov.br.

**Comment by mnt-c** [comment]
Link de possíveis soluções de desbloqueio (por ip solicitante e regra de palavras na url):
https://devcentral.f5.com/questions/waf-blocking-templates-on-upload-50232

**Comment by maxbborges** [comment]
Código de bloqueio do Firewall ao tentar inserir a tag embed no codigo HTML.
Código: 7747752473181494829

**Comment by mnt-c** [comment]
Código de bloqueio do Firewall ao tentar inserir a tag object no codigo HTML.
Código: 7747752473181223680

**Comment by mnt-c** [comment]
Código de bloqueio do Firewall ao tentar inserir a código de publicações do Twitter no código HTML.
Código: 7747752473301980120

**Comment by joenio** [comment]
email solicitando desbloqueio enviado para: bloqueio.de.aplicacoes@presidencia.gov.br

**Comment by mnt-c** [comment]
12138245677907151419
