### ISSUE TITLE
alterar banner brasil+jovem na capa do portal

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#3]
![captura de tela de 2017-11-06 12-36-55](https://user-images.githubusercontent.com/44172/32446186-33ccc850-c2ef-11e7-9e79-20157ebfd053.png)

adicionar outro banner ao lado do banner brasil+jovem (imagem acima), reduzir o banner brasil+jovem, diego barreto preparou as imagens novas (em anexo abaixo).

![botao_site_b j](https://user-images.githubusercontent.com/44172/32446286-8dbc9ee4-c2ef-11e7-91bf-39faf6fa2c90.png)

o banner da imagem acima deve linkar para:
* https://issuu.com/participatorio/docs/revista_brasil_mais_jovem_-_n___1

![botao_site_startup](https://user-images.githubusercontent.com/44172/32446288-8ddf7504-c2ef-11e7-93c3-59cc461f32b4.png)

apontar banner acima para o link:
* http://juventude.gov.br/juventude/noticias/participe-da-consulta-publica-sobre-o-plano-nacional-de-desenvolvimento-de-startups-para-a-juventude

Passos para alterar os banners:
1. Fazer login como administrador do portal
1. Fazer upload das imagens na comunidade juventude: http://juventude.gov.br/juventude
  * subir as imagens na pasta "banners dos programas", caminho: comunidade juventude -> painel de controle -> gerenciar conteúdo -> banners dos programas -> novo conteúdo -> arquivo enviado
1. Acessar Administração -> Blocos laterais
1. Editar o HTML do bloco que contém o banner brasil+jovem (primeira imagem anexada nesta issue)
1. Alterar o HTML, mudar o banner brasil+jovem pelo novo banner e adicionar ao lado o banner startups
  * a largura total da tela é 950px, utilizar cada banner com 450px e deixar sobrando 50px de margem

**Comment by maxbborges** [comment]
Inserido os novos banners com  dimensões de 450px e margin de 12.5px para cada lado de cada imagem.

**Comment by mnt-c** [comment]
Publicado no site do juventude.

**Comment by joenio** [comment]
link para o banner startups: http://juventude.gov.br/startups/consulta-plano-nacional-de-desenvolvimento

**Comment by maxbborges** [comment]
Link do banner StartUp alterado para o novo.
