### ISSUE TITLE
Funcionalidade do botão "Entrar na Comunidade"

### ISSUE THREAD

**Issue by FabioDsg** [IBICT/noosfero#31]
Issue relacionada ao documento PARTICIPATÓRIO2 Relatório das funcionalidades - Usuário e Administrador que se encontra no seguinte link:

https://docs.google.com/document/d/1VcC1l2zpgMBTbvS512IHqHUKLZa3zVIeptdyKzVS2y0/edit?usp=sharing

Tal botão está com parte do texto sobreposto e só funciona caso o usuário esteja logado. Porém não existe uma mensagem ou redirecionamento que informe o usuário, isso faz com que no primeiro contato o botão pareça não ter nenhuma utilidade como descrito no relatório.

Segue o print:

![botaoentrarnacomunidade2](https://user-images.githubusercontent.com/8026759/33375896-b352533c-d4f2-11e7-83ab-56cfdd97cef9.PNG)

**Comment by maxbborges** [comment]
uma possível solução é inserir o seguinte trecho de css no bloco lateral de html puro da comunidade especifica: [join-community.txt](https://github.com/IBICT/noosfero/files/1514519/join-community.txt)


A solução foi testada na comunidade http://juventude.gov.br/plano-nacional-de-juventude e funcionou corretamente.

**Comment by FabioDsg** [comment]
Valeu @maxbborges!

**Comment by luucilia** [comment]
@maxbborges, que gambiarra! Por que você não colocou isso no código do noosfero pra aplicar pra todas as comunidades?

**Comment by maxbborges** [comment]
não podemos alterar o noosfero diretamente ainda, podemos? além de nem sabermos se isso já foi atualizado nas versões atuais.

**Comment by FabioDsg** [comment]
A parte estética do botão fica ok e se resolve com esse código, porém a queixa no documento que gera essa issue é a falta de "ação" ao clicar em entrar na comunidade, não há um aviso, nada acontece, causa no usuário a sensação de que não funciona... Não é intuitivo nessa situação saber que precisa estar logado para que o botão funcione.

Segue um print com um discreto "carregar" infinito:

![carregareterno](https://user-images.githubusercontent.com/8026759/33482770-c9339e46-d681-11e7-86cc-8bd08c85f4a9.PNG)

**Comment by luucilia** [comment]
Eu procurei no código do Noosfero o lugar pra alterar o css dessa parte do "Entrar na comunidade" e está em: **public\stylesheets\blocks\profile-info.scss**

Eu testei só colocando essa parte do código do @maxbborges e funcionou:

#content .profile-info-options a.button.with-text.join-community {
    padding-left: 0px;
    text-align: center;
}

Essa é a imagem de como ficou usando o Noosfero da minha máquina:

![screen shot 2017-12-01 at 11 03 47 am](https://user-images.githubusercontent.com/17516861/33484099-197149a2-d688-11e7-84c8-4fbee9072485.png)

**Comment by joenio** [comment]
isso precisa ser resolvido no tema do juventude, o repositório do tema está em:
* https://gitlab.com/noosfero-themes/juventude

**Comment by joenio** [comment]
@luciliapo como está o andamento dessa issue? Conseguiu fazer as alterações no tema da juventude?

**Comment by luucilia** [comment]
Estamos configurando o ambiente nesse momento e após isso começarei a trabalhar nessa issue.

**Comment by luucilia** [comment]
O arquivo que precisa ser mudado para corrigir o botão "entrar na comunidade" se encontra em **style.css** na página https://gitlab.com/noosfero-themes/juventude.

Basta inserir o código citado anteriormente:
#content .profile-info-options a.button.with-text.join-community {
padding-left: 0px;
text-align: center;
}

Fiz o commit na página do tema e está pendente a aprovação.
