### ISSUE TITLE
Página Iniciativa em Destaques sem conteúdo

### ISSUE THREAD

**Issue by luucilia** [IBICT/noosfero#32]
Página Iniciativa em Destaques: http://juventude.gov.br/juventude/iniciativas

- Falta conteúdo (texto, imagens e vídeos);
- Melhorias propostas:
-- Inserir conteúdo;
-- Melhorar a apresentação da página; 
-- Ou remover a página;

![iniciativa_destaques](https://user-images.githubusercontent.com/17516861/33376038-45a2a750-d4f3-11e7-8a91-42e4a0a156b0.PNG)

**Comment by maxbborges** [comment]
Foi informado pela Estela que a pagina era pra ser usado com outro intuito, entretanto, acabou não sendo usado e que poderia ser desativada. Portanto, a pagina foi desativada e o link foi removido da pagina inicial. A issue foi resolvida.
