### ISSUE TITLE
Evolução da página Brasil Mais Jovem

### ISSUE THREAD

**Issue by FabioDsg** [IBICT/noosfero#34]
Segue em anexo o pptx com parte das novas alterações a serem realizadas na página Brasil Mais Jovem solicitadas pelo Michell:

[BMJ_INSTRUCOES.pptx](https://github.com/IBICT/noosfero/files/1526844/BMJ_INSTRUCOES.pptx)

Em produção.

**Comment by luucilia** [comment]
@maxbborges e @caiomnt , personalizem o menu de links para ficar parecido com o do ID Jovem. Os menus estão verticalmente distribuídos, coloquem eles na horizontal.

Atualmente, está assim:

![barra_bmj](https://user-images.githubusercontent.com/17516861/33556519-54ae953c-d8eb-11e7-95a2-260a06435180.PNG)

Ficar assim:

![barra_idj](https://user-images.githubusercontent.com/17516861/33556619-aa7d508e-d8eb-11e7-881e-e466e47b695a.PNG)

**Comment by maxbborges** [comment]
Foi inserido um bloco de HTML puro com o seguinte CSS: [MenuBrasilMaisJovem.txt](https://github.com/IBICT/noosfero/files/1528123/MenuBrasilMaisJovem.txt)
Além disso foi retirado os ícones (setas) q apareciam antes de cada índice do menu.

Novo formado do menu da pagina Brasil Mais Jovem:
![foto](https://user-images.githubusercontent.com/18174772/33566703-fa747c90-d907-11e7-8183-0e64d1c409a7.PNG)

**Comment by mnt-c** [comment]
Apresentado para o Michell e a solicitação foi aprovada, porém o mesmo solicitou a inserção de item da apresentação de vídeo junto com código embutido do Twitter da página principal.

Ao inserir o elemento foi bloqueada a solicitação pelo WAF e é aguardado a liberação do código 7747752473301980120, para conclusão da tarefa.

**Comment by FabioDsg** [comment]
Foi corrigido o link para o vídeo do YouTube **"embed"** e realizada a tentativa de listar uma **"timeline"** 
segundo a mesma ideia utilizada na página inicial do juventude:

![proposta](https://user-images.githubusercontent.com/8026759/33715762-d4067cfe-db3a-11e7-8ae3-5251ccbc90c5.PNG)

Porém o **"Firewall"** bloqueia a tentativa de uso de qualquer **"Script"** como o que é utilizado nesta página.

Foi deixado um modelo proposto aonde **"falta trabalhar o link do Twitter"** para que o mesmo liste as postagens, da forma atual ao clicar no link ele apenas leva para pagina do Twitter da @SNJuventude.

Segue o print:

![prop_01](https://user-images.githubusercontent.com/8026759/33715963-8e17358e-db3b-11e7-97fa-b3967dc730ec.PNG)


Segue o código utilizado para Twitter:

`<a class="twitter-timeline"
  href="https://twitter.com/SNJuventude">
Tweets by @SNJuventude
</a>`

Segue o código utilizado para Vídeo:

`<iframe width="560" height="315" src="https://www.youtube.com/embed/rVoYpRfWybs" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>`

**Comment by FabioDsg** [comment]
O Michell relatou que não estão conseguindo comentar na página. Foi e está sendo verificado, que acessando a notícia diretamente a opção de comentar está funcionando, porém, ao clicar no link Notícias e acessá-las de forma geral, não aparece opção de comentar.  Porém existe essa opção que leva aos comentários juntamente com a opção de comentar:

![linkcomment](https://user-images.githubusercontent.com/8026759/33942834-5c62e84a-dffe-11e7-9bf5-b26a27f441ad.PNG)

**Comment by mnt-c** [comment]
Foi adicionado um código por meio do RAW HTML:

```CSS
#content .post-comment-button, .page-comment-form, .comment-footer, .display-comment-form {
  display: inline;
}
```

A solução atendeu sobre os comentários.

**Comment by mnt-c** [comment]
Foi realizado algumas melhorias solicitado pelo Michell:

Inclusão de títulos:

- ÚLTIMAS NOTÍCIAS.
- YOUTUBE
- TWITTER

Remoção temporária da aba do Twitter até a aprovação de código a ser inserido pela DITEC.

Alterado link de vídeo para:  https://www.youtube.com/watch?v=0avkjmP6euw

**Comment by FabioDsg** [comment]
Acredito que através do seguinte código, o problema relacionado a time line do twitter embutida foi resolvido:

`<iframe style="width:300px;height:250px;" src="http://tools.classcube.com/embed/twitter/SNJuventude/"></iframe>`

Referência:
https://classcube.com/embed-twitter-timeline/

Segue um print do funcionamento:

![twitter_working](https://user-images.githubusercontent.com/8026759/34044880-f2cd8df4-e18d-11e7-8892-19fa5e5a742f.PNG)

**Comment by FabioDsg** [comment]
Segue um print do funcionamento no celular:

![capture _2017-12-15-11-56-05](https://user-images.githubusercontent.com/8026759/34045752-794b3b4e-e191-11e7-96ef-3e9bf9075a18.png)

**Comment by mnt-c** [comment]
O solicitante Michell pediu para que houvesse a inserção de um banner rotativo na página do Brasil Mais Jovem:

![desktop 1_067](https://user-images.githubusercontent.com/18350825/34054681-2c7878c8-e1b3-11e7-823f-5cd95229c107.png)

No caso foi inserido o banner rotativo contendo imagens referentes as ultimas notícias publicadas.

**Comment by mnt-c** [comment]
Segundo o solicitante Michell não houve aprovação da solução proposta pela equipe e mantém a decisão temporária até a liberação do desbloqueio.
