### ISSUE TITLE
Aniversário 1 ano ID Jovem

### ISSUE THREAD

**Issue by FabioDsg** [IBICT/noosfero#36]
Foi solicitada a criação de uma página no Id Jovem para divulgação e convite a participação do aniversário de um ano do Id Jovem. 

"É necessário estar logado para visualizar a página já que a pedido do Michell a mesma se encontra com privado"

Falta ajustar os links para download e possivelmente o tamanho das imagens, porém com elas foram feitas para o tamanho específico de cada rede social talvez não fique 100% como já pode ser visto.
 
**Ao clicar no link para download está sendo aberta a imagem em uma nova aba ao invés de oferecer a opção "Download"** 

Ainda precisa ser modificado para que seja oferecida a opção de realizar o "Download"

Segue o link da página:
http://juventude.gov.br/idjovem/id-jovem-aniversario-1-ano

Caminho para o conteúdo:
http://juventude.gov.br/idjovem/id-jovem-personaliza

**Comment by FabioDsg** [comment]
O problema **Ao clicar no link para download está sendo aberta a imagem em uma nova aba ao invés de oferecer a opção "Download"** foi solucionado aplicando a sugestão do @caiomnt de utilizar o imgur com sua função de download como no código abaixo:

`https://imgur.com/download/jm7aJXe`


As imagens por ser tratarem de uma "divulgação" e não conter conteúdo confidencial ou de propriedade "privada" foram hospedadas no https>//imgur.com.

Foram realizados vários testes para resolver o problema  **Ao clicar no link para download está sendo aberta a imagem em uma nova aba ao invés de oferecer a opção "Download"** .

Foi realizado o teste hospedando as imagens no Google drive, funcionou em partes, no browser a imagem é aberta em uma nova aba oferecendo algumas opções dentre elas a de "Download", porém em dispositivos móveis, é solicitado o login em uma conta do Google fazendo com que não seja uma solução prática, tal opção atenderia o proposto caso o usuário estivesse acessando em modo anônimo o que não é comum e  prático. 

Foram realizadas diversas tentativas com a soluções padrões, códigos que funcionam normalmente como **href="path/to/file"** seguido da opção **download=""** assim como **target="_blank"**,  porém, ao serem aplicados no código do artigo, tal código é apagado ao clicar em salvar. Não apresenta mensagem de erro ou qualquer outra, apenas some do código e não funciona.
  
Segue um arquivo contendo todos os códigos testados:

 
[CodeTest.txt](https://github.com/IBICT/noosfero/files/1531300/CodeTest.txt)


A issue está aguardando confirmação de que o problema foi resolvido.

**Comment by maxbborges** [comment]
Foi apresentado para o Michel a opção funcional de download dos banners, com isso foi proposto o uso do imgur.com e ele aceitou. Os links estão todos acessíveis e funcionais.
