### ISSUE TITLE
Usuários não logados não conseguem fazer comentários

### ISSUE THREAD

**Issue by luucilia** [IBICT/noosfero#37]
Na documentação do noosfero diz que usuários não logados podem fazer comentários (http://softwarelivre.org/doc/user/commenting).

Entretanto, na consulta pública do Plano Nacional da Juventude, apenas os usuários logados podem comentar, sendo que para usuários não logados não aparece nada, nem sequer um aviso. Logo, deve-se habilitar para que usuários não logados comentem ou alguma solução alternativa. 

Tela para usuários não logados:

![no_comments](https://user-images.githubusercontent.com/17516861/33610550-f72551b2-d9b2-11e7-9d1f-350510da4f2b.png)

**Comment by luucilia** [comment]
Fui em Painel de Controle -> Informações e Configurações da Comunidade

Marquei essa opção:

![comments](https://user-images.githubusercontent.com/17516861/33611387-5b55f4d2-d9b5-11e7-8fc1-9bbd2114f537.PNG)

E continua sem funcionar.

**Comment by mnt-c** [comment]
Numa versão mais recente instalada localmente do Noosfero, foi possível comentar sem a necessidade de estar logado. A mesma aparece um campo de usuário e E-mail para realizar o comentário:

![comentario0](https://user-images.githubusercontent.com/18350825/33619126-8ce58ed4-d9cb-11e7-93fb-676ccddab586.jpg)


Fiz então um teste com um usuário válido e outro com usuário anônimo:

![comentario1](https://user-images.githubusercontent.com/18350825/33619133-920a2910-d9cb-11e7-8024-e54a952a4d0d.jpg)


Tentei encontrar um commit no repositório oficial que possa ser a possível atualização, mas não obtive êxito. Ainda na procura, caso encontre editarei esse mesmo post.

**Comment by luucilia** [comment]
Considerando a ausência dessa funcionalidade nessa versão do Noosfero, adicionou-se como medida provisória um texto com os links para se "Cadastrar" ou "Entrar na sua conta", logo abaixo dos 11 eixos da consulta pública, para deixar claro ao usuário a necessidade de login para efetuar comentários.

Print da tela de como ficou:

![comment_prov](https://user-images.githubusercontent.com/17516861/33716250-9207d760-db3c-11e7-9887-18de99783e4d.PNG)

**Comment by mnt-c** [comment]
O problema foi resolvido através de inserção de código na funcionalidade de RAW HTML:

![image](https://user-images.githubusercontent.com/18350825/33954705-39e1eb00-e020-11e7-9503-d11918b277d5.png)


Solução adotada:

```CSS
#content .post-comment-button, .page-comment-form, .comment-footer, .display-comment-form {
  display: inline;
}
````
