### ISSUE TITLE
Relatório de acessos ao portal da juventude via Piwik

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#41]
A DITEC mantém um Piwik com coleta de dados de acesso ao portal da juventude, precisamos descobrir como acessar.

**Comment by FabioDsg** [comment]
Foi enviado um e-mail com o nome completo e usuário de rede de todos os membros da equipe como solicitado pela Nayanne para que seja gerado o acesso ao Piwik.

**Comment by FabioDsg** [comment]
Foi realizado o cadastro de todos integrantes da equipe conforme solicitado. Todos estão com acesso ao Piwik. 

Estarei reencaminhando o e-mail com acessos para os demais.
