### ISSUE TITLE
Documentação Portal da Juventude

### ISSUE THREAD

**Issue by maxbborges** [IBICT/noosfero#42]
Foi solicitado a criação de um documento passo a passo do portal da juventude, para que fosse além de um mapa do site, fosse também um tutorial das funcionalidades disponíveis no portal.

**Comment by FabioDsg** [comment]
Valeu @maxbborges! Estarei lendo com calma e possivelmente contribuindo.

**Comment by luucilia** [comment]
O documento oficial foi criado e se encontra em: http://revistasnj.ibict.br/ojs_snj/index.php/snj/article/view/81.
