### ISSUE TITLE
Limpar Histórico de Imagens

### ISSUE THREAD

**Issue by FabioDsg** [IBICT/noosfero#43]
Ao tentar inserir uma nova imagem no "Slide Show" que é apresentado na página inicial, é mostrada uma lista muito grande de imagens como pode ser observado abaixo:

![list_imagens](https://user-images.githubusercontent.com/8026759/35040949-2e7f713c-fb6a-11e7-8e07-50320705a937.png)

Ao verificar a possibilidade de "apagar" as imagens mais antigas, descobre-se que há um volume considerável para procurar imagem por imagem. Encontram-se armazenadas de forma desorganizadas o que dificulta identificar qual poderia ser apagada ou não.

![num_imagens](https://user-images.githubusercontent.com/8026759/35041068-a550e476-fb6a-11e7-98b0-0e0093ae9de3.PNG)

**Comment by luucilia** [comment]
Foi constatado que o problema não se trata do histórico e sim da grande quantidade de imagens armazenadas no diretório de forma que ao adicionar um banner no carrossel aparece uma lista imensa. 

Como, no momento, excluir as imagens não é uma opção, essa issue será fechada e caso haja alguma soução, ela poderá ser reaberta.
