### ISSUE TITLE
Função "Divulgar"

### ISSUE THREAD

**Issue by estelanm** [IBICT/noosfero#44]
A função "divulgar" não está funcionando corretamente. Após a aprovação da divulgação do post em outras comunidades, o post não é publicado automaticamente. Atualmente, estamos publicando manualmente, comunidade por comunidade.

**Comment by maxbborges** [comment]
@estelanm, você chegou a verificar na parte de aprovação de postagem nessa comunidade que você escolheu publiar? Houve um problema em que não publicava em outras comunidades, mas isso ocorria pois é necessario fazer a aprovação da publicação em cada comunidade separadamente.

**Comment by estelanm** [comment]
Sim, mesmo depois de aprovado, o post não aparece.

**Comment by maxbborges** [comment]
qual foi a ultima postagem que você divulgou e para qual comunidade foi?

**Comment by estelanm** [comment]
Seria essa http://juventude.gov.br/juventude/noticias/amapa-representara-regiao-norte-na-ultima-audiencia-publica-do-novo-pnj
Divulguei na comunidade : http://juventude.gov.br/plano-nacional-de-juventude
Porém, não foi publicado e tive que pulicar manualmente...

**Comment by maxbborges** [comment]
Para realizar uma divulgaçao é necessario publicar em uma comunidade filha como o Plano nacional de juventude para depois ser divulgada na comunidade mãe q é a Juventude. Portanto, apos ser feito a divulgacao, será necessario ir no painel de controle da comunidade juventude, entrar na opçao tarefas e aprovar a publicação. Poderia testar?

**Comment by luucilia** [comment]
@estelanm, eu testei o que você comentou e a função divulgar funcionou comigo.

Eu fiz da seguinte forma:

1. Cliquei em Divulgar o post do artigo "Amapá representará região Norte na última audiência pública do novo PNJ".

2. Apareceu a janela das opções de publicação, eu selecionei para publicar na comunidade Brasil Mais Jovem.

![divulgar](https://user-images.githubusercontent.com/17516861/35150938-7c51d536-fd03-11e7-8ce2-d50ec6731de7.png)

3. Após clicar em Divulgar na comunidade Brasil Mais Jovem, aparece a mensagem: "Sua requisição de publicação foi enviada com sucesso" e note que aparece uma notificação em laranja indicando que a divulgação está pendente.

![divulgar_msg](https://user-images.githubusercontent.com/17516861/35151393-48de7c34-fd05-11e7-8357-03e5fe53a82b.png)

4. Cliquei na notificação em laranja e aparece a seguinte tela:

![aceitar_divulgacao](https://user-images.githubusercontent.com/17516861/35151594-125f485e-fd06-11e7-9ad6-e3acd3afda79.PNG)

5. Selecionei "Aceitar" e escolhi a opção de publicar em notícias.

![aceitar_divulgacao_pg](https://user-images.githubusercontent.com/17516861/35151671-5984ca7e-fd06-11e7-8e7e-504e8c4ff996.png)

6. Post publicado em Notícias na comunidade Brasil Mais Jovem.

![publicado](https://user-images.githubusercontent.com/17516861/35151730-9dcd65ba-fd06-11e7-8d18-5e64d5579369.PNG)


@estelanm, se você tentar novamente e não funcionar, ou se algum desses passos não funcionarem, eu e o @FabioDsg podemos te auxiliar na sua sala, só falar com a gente.

**Comment by luucilia** [comment]
A função "Divulgar" foi testada com a @estelanm e está funcionando normalmente, caso hajam mais problemas à respeito dessa função a issue será reaberta.
