### ISSUE TITLE
Botão "Remove Field" do Custom Forms

### ISSUE THREAD

**Issue by maxbborges** [IBICT/noosfero#47]
O Botão "Remove Field" do plugin custom forms não remove o campo designado. É possivel adicionar um novo item no formulario, entretanto não é possivel remover:

![captura de tela de 2018-01-24 16-00-19](https://user-images.githubusercontent.com/18174772/35348858-7a5c9b50-0120-11e8-882c-126baebcfce2.png)

**Comment by mnt-c** [comment]
Foi reproduzido o erro e houve aplicação em Survey do plugin custom_forms.

O problema foi identificado no arquivo de javascript do próprio plugin  em:

./plugins/custom_forms/public/javascripts/field.js

Peguei como base o que era aplicado para remover botões do Poll do plugin custom forms(./plugins/custom_forms/public/javascripts/poll.js), e alterei o código  encontrando a solução para o problema:

```JS
$(document).ready(function() {
  $("a.remove-field").live('click', function() {
    var field = $(this).closest('li');
    var destroy_field = jQuery('input.destroy-field', field);
    field.fadeOut(500, function() {
      if(destroy_field.length == 1){
        destroy_field.val(1);
        field.hide();
      }
      else
        field.remove();
    });
    return false;
  });
```

Após a inserção do código, a remoção do campo funcionou normalmente em Survey.

**Comment by mnt-c** [comment]
Fiz um teste removendo um campo, porém contendo submissões e no caso se remover o campo também irá remover as respostas envolvidas daquele campo no banco de dados.

![screenshot from 2018-02-19 16-01-19](https://user-images.githubusercontent.com/18350825/36393496-a090cd96-158e-11e8-9e44-afb706f8686a.png)

Na figura acima eu fiz a remoção do campo 'campodelete'.

![screenshot from 2018-02-19 16-18-40](https://user-images.githubusercontent.com/18350825/36393965-c03c5b90-1590-11e8-92de-00220f47f25c.png)

Aqui vemos a diferença com remoção no banco.


Neste caso acho poderia ser incluido um aviso para o usuário que está utilizando esse recurso alertando o risco antes de remover e mostrando à ele se ele quer realmente prosseguir.

**Comment by mnt-c** [comment]
Foi solicitado o merge request da solução proposta (https://gitlab.com/caiomnt/noosfero/commit/72f35cbdbcfbe687ea2470468ee10cb52eefd3be).

Aguardando aprovação.

**Comment by joenio** [comment]
aguardando aprovação do merge-request

**Comment by mnt-c** [comment]
O código somente removia o text field da survey, porém não removia as opções de seleções.

Foi atualizado o merge-request (https://gitlab.com/noosfero/noosfero/merge_requests/1406) com as configurações e aguardando aprovação
