### ISSUE TITLE
bug com rss em ambiente noosfero fechado

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#51]
bug feed rss doesn't work in closed environment: https://gitlab.com/noosfero/noosfero/issues/28

**Comment by mnt-c** [comment]
Tinha realizado alguns testes com o ambiente 'fechado'(sem acesso do conteudo aos visitantes), porém não consegui reproduzir a falha. 

Dos resultados obtidos:

- Criei uma comunidade e gerei artigos para a mesma
- Acessei seu RSS logado e deslogado
- Fechei o acesso.
- Acessei seu RSS apenas logado.

Teste de RSS de uma comunidade de testes:

![screenshot from 2018-02-20 13-30-45](https://user-images.githubusercontent.com/18350825/36497991-bd2c5b30-171b-11e8-9994-810bf1691690.png)

Configurando o ambiente fechado:

![screenshot from 2018-02-20 15-59-14](https://user-images.githubusercontent.com/18350825/36497974-afd46d38-171b-11e8-9059-aabf7af3c79c.png)

Acesso bloqueado mostrando a página de login ao visitante

![screenshot from 2018-02-21 15-31-03](https://user-images.githubusercontent.com/18350825/36498209-5fdd8bce-171c-11e8-9563-33f3b3a69e9f.png)

**Comment by mnt-c** [comment]
Consegui reproduzir a falha, utilizando o leitor de RSS que vem imbutido no Firefox e com uma extensão chamada FeedBro.

FeedBro sem o bloqueio de RSS:

![screenshot from 2018-02-26 15-42-15](https://user-images.githubusercontent.com/18350825/37296035-8930ff48-25f8-11e8-82ef-2d94b08eba64.png)

FeedBro com o bloqueio de RSS:

![screenshot from 2018-02-26 15-41-19](https://user-images.githubusercontent.com/18350825/37296072-9fa01156-25f8-11e8-810e-0037ca83e216.png)

Quando é utilizado os campos de usuário e senha ele funciona como se fosse uma autenticação normal de HTTP com cookie e sessão.

Ao olhar a resposta com o curl no ambiente ele retorna um código **302 Not Found** com a resposta text/html e não o formato XML e redireciona para a página de login. Quando é usado os tokens necessários ele responde corretamente ao RSS.

![image](https://user-images.githubusercontent.com/18350825/37295899-29c93caa-25f8-11e8-9b9b-aa6789039bc5.png)

Nas especificações do RSS não mostra o código de erros HTTP envolvidos. Encontrei no https://www.mnot.net/rss/tutorial/ que os códigos 301, 410 e 404 são mais usados.

Existe também um formato de feed similar e mais documentado conhecido como Atom, onde já funciona em alguns leitores de RSS. Nele ele informa que o 401 e 403 poderia ser utilizado para bloqueio do acesso.

**Comment by maxbborges** [comment]
A barra de tags está sobrescrevendo o menu lateral, como segue a imagem abaixo.
Esse bug aparece quando é acessado o painel de controle, depois em tarefas
![captura de tela de 2018-03-12 14-17-41](https://user-images.githubusercontent.com/18174772/37298837-3fbda8cc-2600-11e8-80cf-17ca91a59f25.png)

**Comment by joenio** [comment]
fechando issue uma vez que iremos refatorar o noosfero para incluir funcionalidade de compartilhar conteúdo privado com token.
