### ISSUE TITLE
executar todos os testes do noosfero e corrigir eventuais falhas

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#52]
rake test:all not running all tests: https://gitlab.com/noosfero/noosfero/issues/165

**Comment by maxbborges** [comment]
Foi criado um novo container, com uma instalação limpa do noosfero, sem o tema do juventude ser aplicado. No container foi executado o teste com o comando "rake teste:all", com duração de cerca de 27 minutos o teste apresentou 19 falhas e nenhum erro. Segue a lista dos testes que falharam:

![captura de tela de 2018-02-07 16-24-56](https://user-images.githubusercontent.com/18174772/35934023-800effd0-0c23-11e8-8357-577cfeb750f7.png)

- [x] FAIL["test_successfull_registration", UserRegistersAtTheApplicationTest, 21.566773804]
- [x] FAIL["test_should_link_to_uncategorized_assets_at_site_root", AssetsMenuTest, 23.784142197]
- [x] FAIL["test_should_base_theme_uses_config_to_specify_more_then_an_icon_theme", ApplicationHelperTest, 151.735631214]
- [x] FAIL["test_should_base_theme_uses_default_icon_theme", ApplicationHelperTest, 151.774775481]
- [x] FAIL["test_should_nil_javascript_theme_when_no_exists_theme", ApplicationHelperTest, 158.243396513]
- [x] FAIL["test_should_nil_theme_option_when_no_exists_theme", ApplicationHelperTest, 158.428847374]
- [x] FAIL["test_should_build_menu_to_the_community_panel_of_communities_the_user_can_manage_if_enabled", ProfileControllerTest, 205.178669814]
- [x] FAIL["test_should_build_menu_to_the_enterprise_panel_if_enabled", ProfileControllerTest, 205.834154082]
- [x] FAIL["test_should_display_list_of_communities_to_manage_on_menu_if_enabled", ProfileControllerTest, 215.659852133]
- [x] FAIL["test_should_show_a_link_to_own_control_panel", ProfileControllerTest, 247.542549205]
- [x] FAIL["test_should_add_plugin_items_on_user_menu", ApplicationControllerTest, 805.921668663]
- [x] FAIL["test_should_include_content_in_the_beginning_of_body_supplied_by_plugins_regardless_it_is_a_block_or_html_code", ApplicationControllerTest, 807.880653761]
- [x] FAIL["test_should_include_content_in_the_ending_of_head_supplied_by_plugins_regardless_it_is_a_block_or_html_code", ApplicationControllerTest, 807.930299633]
- [x] FAIL["test_creation_of_a_new_article", ManageDocumentsTest, 1041.582155187]
- [x] FAIL["test_removing_an_article", ManageDocumentsTest, 1041.827074119]
- [x] FAIL["test_update_of_an_existing_article", ManageDocumentsTest, 1042.061911885]
- [x] FAIL["test_should_add_class_to_body_tag_if_is_on_profile_homepage", ContentViewerControllerTest, 1046.975630049]
- [x] FAIL["test_should_provide_a_link_to_make_the_user_authentication", HomeControllerTest, 1386.622363988]
- [x] FAIL["test_should_have_a_default_image_if_thumbnails_were_not_processed", UploadedFileTest, 1407.10375996]

**Comment by maxbborges** [comment]
Foram feitos novos testes individuais em cada teste com falha, e nenhum apresentou erro.

**Comment by maxbborges** [comment]
Em um novo teste realizado com o comando "rake teste:all", apresentou 10 falhas.
Acredita-se que um teste pode estar influenciando no teste seguinte, pois os erros são apresentados de forma aleatória e nem sempre o mesmo erro é apresentado.
