### ISSUE TITLE
Novas comunidades

### ISSUE THREAD

**Issue by estelanm** [IBICT/noosfero#55]
Puxar as três novas comunidades, Dig. Juv. Rural, LGBT e Inova Jovem mais para cima, na área de destaque. Elas devem aparecer primeiro que as outras. :)

**Comment by luucilia** [comment]
As comunidades foram movidas para cima como mostra a imagem: 

![confira_tambem](https://user-images.githubusercontent.com/17516861/35913296-51300138-0be6-11e8-9a87-bd2c94e17f0d.png)
