### ISSUE TITLE
Brasil Mais Jovem 1ª edição

### ISSUE THREAD

**Issue by estelanm** [IBICT/noosfero#56]
Disponibilizar um banner de destaque para a primeira edição da revista (Issu) dentro da comunidade Brasil Mais Jovem. Vou enviar um banner com arte.

**Comment by maxbborges** [comment]
Aguardando o Banner para efetuar as modificações.

**Comment by estelanm** [comment]
![whatsapp image 2018-02-07 at 16 21 56](https://user-images.githubusercontent.com/34688898/35935313-41d9bb48-0c27-11e8-82e4-11dae6b347ed.jpeg)

Consegue pegar daqui? Se não, me passe seu email....

**Comment by FabioDsg** [comment]
O banner foi adicionado conforme solicitado. Aguardando um feedback em relação ao título.
http://juventude.gov.br/profile/brasil-mais-jovem

**Comment by luucilia** [comment]
Tarefa realizada.
