### ISSUE TITLE
substituir caracteres dash por -

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#57]
* issue no repositório oficial do noosfero: https://gitlab.com/noosfero/noosfero/issues/3
* caracteres dash: https://en.wikipedia.org/wiki/Dash

**Comment by maxbborges** [comment]
Foram criados 3 novos artigos, cada um usando um tamanho de dash diferente. Em nenhum dos 3 tipos testados foi apresentado o problema relatado.

Artigos criados:
![captura de tela de 2018-02-14 15-43-13](https://user-images.githubusercontent.com/18174772/36219415-6a1e7374-119e-11e8-9d53-877a518eb40d.png)

Pagina de apresentação dos artigos:
![captura de tela de 2018-02-14 15-46-27](https://user-images.githubusercontent.com/18174772/36219397-5b7cd716-119e-11e8-9846-a55360f458c0.png)

**Comment by joenio** [comment]
@maxbborges massa, alguém resolveu a issue antes e não fechou a issue no upstream. eu tb testei agora e notei que realmente o problema n ocorre! valeu!!!
