### ISSUE TITLE
Testar o ambiente de homologação do Participa

### ISSUE THREAD

**Issue by luucilia** [IBICT/noosfero#58]
Conforme o email enviado pela Nayanne, o link do ambiente em homolagação é: http://participa-hom.presidencia.gov.br

Testes:

- [x] 1. Aplicar tema em Angular
- [ ] 2. Criar usuário
- [x] 3.1 Criar comunidade
- [x] 3.2 Aceitar solicitação para criar comunidade
- [x] 3.3 Rejeitar solicitação para criar comunidade
- [x] 4. Trocar foto de perfil
- [x] 5. Trocar foto de capa
- [x] 6. Criar discussão
- [x] 7. Fazer solitação de amizade
- [ ] 8. Adicionar imagens
- [x] 9. Excluir comunidade
- [x] 10. Criar artigo
- [x] 11. Comentar artigo
- [x] 12.1 Exportar comentários de uma discussão
- [ ] 12.2 Exportar comentários de um artigo #59 
- [x] 13. Rejeitar criação de uma comunidade
- [x] 14. Adicionar amigo
- [x] 15. Aceitar solicitação de amizade
- [ ] 16.1 Editar modo: Bloco html 
- [x] 16.2 Editar modo: Nuvem de tag 
- [ ] 16.3 Editar modo: Marcadores interessantes 
- [x] 16.4 Editar modo: Conteúdo Recente 
- [x] 16.5 Editar modo: Lista de Link 
- [x] 16.6 Editar modo: Imagem de perfil 
- [x] 16.7 Editar modo: Highlights 
- [x] 16.8 Editar modo: Bloco de Menu 
- [x] 16.9 Editar modo: Friends 
- [x] 16.10 Editar modo: Statistics 
- [ ] 16.11 Editar modo: Breadcrumbs Block 
- [ ] 16.12 Editar modo: Display Content 
- [ ] 16.13 Editar modo: Video 
- [ ] 16.14 Editar modo: Evento 
- [x] 16.15 Editar modo: Bloco de Comunidades
- [ ] 17. Agenda
- [ ] 18. Blog
- [x] 19. Tags
- [ ] 20. Convidar amigos
- [x] 21. Procurar amigos
- [x] 22. Sala de reunião
- [ ] 23. Bloco de anotação
- [x] 24. Alterar Layout Template
- [ ] 25. Convidar pessoas para entrar na comunidade secreta
 

Mais testes serão acrescentados.

**Comment by maxbborges** [comment]
Ao criar um novo usuário  ele informa o seguinte erro:
![captura de tela de 2018-02-14 14-07-42](https://user-images.githubusercontent.com/18174772/36214373-7bedec96-1190-11e8-9d82-cd68d36ec078.png)

Entretanto, a pagina não apresenta nenhuma campo para confirmação se é robo ou não.
Apresentando apenas o campo de aceitação dos termos de uso.

**Comment by mnt-c** [comment]
Parece que possui alguns links que estão apontando para algum servidor de homologação antigo.

****Testei novamente foi solucionado** ✔

**Comment by FabioDsg** [comment]
Foi constatado que após a criação de um post, ao tentar acessá-lo, é gerado um código na url fazendo com que o usuário não consiga ter acesso. 

Segue o exemplo:
Url gerada adiciona “%2F” ao invés de “/”: 
![link_error_02](https://user-images.githubusercontent.com/8026759/36254182-445b6bcc-1231-11e8-840b-8e3b00fb8a13.png)

Url correta:
![link_error_01](https://user-images.githubusercontent.com/8026759/36254195-56a04302-1231-11e8-951c-e35000446e44.png)

**Comment by FabioDsg** [comment]
Usuário consegue acessar modo de edição mesmo não estando logado. 

Segue o print:
![botao_edit_funciona_semestarlogado](https://user-images.githubusercontent.com/8026759/36254352-fa4a58a8-1231-11e8-9dac-45c61d204e00.png)

![autentic01](https://user-images.githubusercontent.com/8026759/36308814-4ca59a68-1309-11e8-9ac0-081e2364f1eb.png)

**Comment by luucilia** [comment]
Não existe a opção de fazer upload de imagens na Galeria. O botão "Edit" apenas edita o módulo da Galeria e não oferece  a opção de adicionar imagens por meio de upload.

![galeria](https://user-images.githubusercontent.com/17516861/36256279-619ecee2-1239-11e8-8e28-eead3299315d.png)

**Comment by luucilia** [comment]
Erro ao tentar aceitar a criação de uma comunidade. Testou-se a funcionalidade de rejeitar a comunidade e funcionou com sucesso, porém a de aceitar retornou erro.

![task](https://user-images.githubusercontent.com/17516861/36259144-5afdfd28-1244-11e8-8635-faa8164561d8.png)

**Comment by FabioDsg** [comment]
O bloco “HTML puro”, marcadores interessantes, Breadcrumbs Block, Display Content, Video e Evento estão sem funcionalidade uma vez que não existe opção para edição de sua funcionalidade. A única opção editável é o título do bloco.

Segue o print:
![html_puro](https://user-images.githubusercontent.com/8026759/36307191-318dce6e-1302-11e8-87af-d8d6f637cd2c.png)

![html_puro_2](https://user-images.githubusercontent.com/8026759/36307203-37101b4e-1302-11e8-9231-e3e35bd138b8.png)

**Comment by luucilia** [comment]
Os links para Agenda, Blog, Convidar amigos, e Bloco de anotação apontam para páginas que não existem ou redirecionam para a página inicial.

![links](https://user-images.githubusercontent.com/17516861/36310521-7382cf92-130f-11e8-9071-638bcdcf38ec.png)

**Comment by mnt-c** [comment]
Ao escolher o tema angular em uma comunidade, a mesma apresenta lentidão ao abrir a página que possui o tema incluido.

**Comment by mnt-c** [comment]
Ao criar uma nova comunidade no tema padrão, é apresentado uma caixa com o fundo amarelo informando a participação da comunidade, mas a mesma aparece para quem já é integrante e o seu link para realizar a participação não teve tratamento de variavel na url. 

No tema do angular a caixa aparece por poucos segundos ao carregar a página.

![screenshot from 2018-03-09 15-39-23](https://user-images.githubusercontent.com/18350825/37223829-83d7e376-23b0-11e8-87f3-ecc18bd6d428.png)


URL gerada não tratada:

![screenshot from 2018-03-09 15-37-04](https://user-images.githubusercontent.com/18350825/37223994-f8a176c2-23b0-11e8-85b2-eff541387988.png)

**Comment by mnt-c** [comment]
Ao criar um novo artigo alguns icones não possuem nomes amigaveis ao criar o conteúdo de texto. Há um código "&nbps" ao fim da criação do artigo e ser criado o artigo se a quantidade de caracteres for consideravel ele não possui uma quebra de linha.

 Icones:

![screenshot from 2018-03-08 15-27-28](https://user-images.githubusercontent.com/18350825/37224254-af190960-23b1-11e8-9ffb-f669b0bc3fa4.png)

Código visivel:

![screenshot from 2018-03-09 13-37-41](https://user-images.githubusercontent.com/18350825/37224580-afdbd886-23b2-11e8-85b0-cebda0efaf8f.png)

Texto sem quebra de linha(o mesmo ocorre no tema do angular):

![screenshot from 2018-03-09 15-57-03](https://user-images.githubusercontent.com/18350825/37224557-9f378f20-23b2-11e8-9a74-c3ce109f70f7.png)

**Comment by maxbborges** [comment]
A barra de tags está sobrescrevendo o menu lateral, como segue a imagem abaixo.
Esse bug aparece quando é acessado o painel de controle, depois em tarefas

![captura de tela de 2018-03-12 14-17-41](https://user-images.githubusercontent.com/18174772/37299009-d6046b86-2600-11e8-80c1-7445cc49b554.png)

**Comment by maxbborges** [comment]
Ícone de remover amigos não é apresentado. Aparece apenas um quadrado sem nenhum ícone ou informação:

![captura de tela de 2018-03-12 14-26-01](https://user-images.githubusercontent.com/18174772/37299201-6acb6184-2601-11e8-982e-662020f2e041.png)

**Comment by maxbborges** [comment]
Ao tentar cria uma nova comunidade usando o tema do angular, o botão Salvar Alteração (Botão usado para criar a comunidade) n tem nenhum efeito, não criando a comunidade.

![captura de tela de 2018-03-12 15-17-24](https://user-images.githubusercontent.com/18174772/37301883-b3647a82-2608-11e8-9847-0c5bea70e6b9.png)

**Comment by mnt-c** [comment]
Ao entrar numa comunidade no tema do Angular é retornado uma chamada de função não uma mensagem de sucesso.

![image](https://user-images.githubusercontent.com/18350825/37303747-2fbc1c02-260e-11e8-8876-3f56f6d31fbb.png)

**Comment by mnt-c** [comment]
Em uma comunidade não é posível criar uma discussão a mesma gera um erro  ao criar:

![image](https://user-images.githubusercontent.com/18350825/37304377-2ddd62ae-2610-11e8-833c-10731d775614.png)

****Testei novamente foi solucionado a criação da discussão ✔**

Porém ao acessar a discussão foi retornado um erro 500: 

![screenshot from 2018-03-14 12-55-01](https://user-images.githubusercontent.com/18350825/37414106-259028de-2787-11e8-8cd3-02201a810c95.png)

**Comment by luucilia** [comment]
Erro ao criar um novo usuário, aparece a mensagem "Certifique-se de que você fez o teste para confirmar que você não é um robô.", sendo que ao preencher os campos não existe nenhum captcha ou algo semelhante, impossibilitando a criação de um novo usuário.

![robo](https://user-images.githubusercontent.com/17516861/37340036-744ca7be-269b-11e8-953a-444f178032f7.png)

**Comment by mnt-c** [comment]
Ao entrar em um comunidade que tenha tema angular, a sessão de usuário que foi autenticada em outro tema não fica mantida e ao logar com o tema do angular não fica mantido a sessão no tema padrão.

![peek 2018-03-14 14-38](https://user-images.githubusercontent.com/18350825/37420448-906406f4-2795-11e8-8bd8-26aad2950d6f.gif)

**Comment by joenio** [comment]
a avaliação final é de que o tema angular está ainda muito imaturo e com muitos bugs, iremos avaliar o nosofero-responsivo como alternativa.
