### ISSUE TITLE
avaliar noosfero responsivo

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#62]
repositório: https://gitlab.com/pedrodelyra/noosfero

**Comment by FabioDsg** [comment]
Foi identificado que as implementações em relação ao tema responsivo, foram realizadas diretamente no código do Noosfero e não em forma de plugin como esperado, o que para o momento não atende a proposta. Aguardando confirmação para fechar a issue.

**Comment by joenio** [comment]
@FabioDsg porque era esperado que fosse plugin?

**Comment by FabioDsg** [comment]
Acredito que me expressei de forma errada ao utilizar o termo “plugin” e entendi errado a ideia.

**Comment by FabioDsg** [comment]
O projeto está muito bom, layout bonito, parece estar maduro e funcionando com fluidez. A última atualização, solucionou alguns bugs, como o botão salvar que não executava a função, porém mesmo após a atualização, ao menos na minha instalação local, alguns ícones continuam não aparecendo corretamente, o que após uma investigação, parece ser uma instabilidade relacionada a nome dos atributos. 

Exemplo ícone de blog:

Código atual: **< i class=”fa fa-newspaper-o”></i>** funcionou na máquina do @joenio, porém para funcionar na minha máquina, o código precisou ser alterado conforme:  
**< i class=”far fa-edit”></i>**

![icon-error](https://user-images.githubusercontent.com/8026759/38502385-9731690e-3be5-11e8-87c2-956db08e849e.png)

Após alteração:

![blog-icon](https://user-images.githubusercontent.com/8026759/38502440-c3ce7254-3be5-11e8-81b1-0ded6ca4e984.png)

**Comment by FabioDsg** [comment]
Ainda estou testando a funcionalidade de criar consulta pública. Ativei o plugin community_track
via:
**./script/noosfero-plugins enable plugins/community_track**, o status aparece como ativo ao rodar:

**./script/noosfero-plugins status**, porém mesmo após reiniciar o serviço, não encontrei a opção de trilha ou semelhante.
