### ISSUE TITLE
Bloco CustomForms no Environment

### ISSUE THREAD

**Issue by maxbborges** [IBICT/noosfero#64]
Na edição de blocos laterais do ambiente environment, quando habilitado o plugin do CustomForms, é apresentado para inserção dois novos blocos, o bloco polls e o bloco surveys. Entretanto, o CustomForms busca polls e surveys criadas no perfil, e o ambiente environment não está atrelado a nenhum perfil, não inserindo o bloco e apresentando erro após atualizar a pagina.

Tela de edição de blocos laterais do ambiente:
![captura de tela de 2018-03-08 15-53-20](https://user-images.githubusercontent.com/18174772/37170185-ec1b6192-22e8-11e8-8112-3b8cded1e7fa.png)

Novos blocos disponíveis para inserção:
![captura de tela de 2018-03-08 15-54-36](https://user-images.githubusercontent.com/18174772/37170246-1623e4d2-22e9-11e8-8b80-48e34f07f967.png) ![captura de tela de 2018-03-08 15-54-42](https://user-images.githubusercontent.com/18174772/37170248-18e0b2cc-22e9-11e8-923f-46cc333b1ff4.png)

Erro apresentado ao atualizar a pagina após inserir um dos blocos do CustomForms:
![captura de tela de 2018-03-08 15-55-52](https://user-images.githubusercontent.com/18174772/37170305-40273130-22e9-11e8-988b-472abba00ba6.png)

**Comment by maxbborges** [comment]
Cada plugin que insere novas opções de blocos laterais, possui o campo:
``` RUBY
  def self.extra_blocks
    {
    }
  end
```

O Custom Forms, cria 2 novos blocos, são eles o Survey e o Polls:
``` RUBY
  def self.extra_blocks
    {
      CustomFormsPlugin::SurveyBlock => { },
      CustomFormsPlugin::PollsBlock => { }
    }
  end
```
Os parâmetros entre { } define em quais páginas esses blocos serão criados, quando estão em branco, é criado em todas as paginas que possui blocos laterais. Entretanto, o plugin usa os dados criados em cada comunidade para criar uma lista específica para ela, no Environment também estava criando os blocos, entretanto esses blocos criados no Environment não estavam vinculados a nenhuma comunidade, apresentando erro https://github.com/IBICT/noosfero/issues/64#issue-303592441 , para corrigir foi editado para: 
``` RUBY
  def self.extra_blocks
    {
      CustomFormsPlugin::SurveyBlock => { :type => Community },
      CustomFormsPlugin::PollsBlock => { :type => Community }
    }
  end
```

Assim, os blocos são criados apenas nas comunidades, corrigindo o problema.

**Comment by joenio** [comment]
pendente implementar testes.

**Comment by joenio** [comment]
vamos continuar essa issue na Sprint 5 #80

**Comment by maxbborges** [comment]
Aguardando aprovação do merge:
https://gitlab.com/maxbborges/noosfero/commit/84878116685b50ca75ef51f8bd719b3d79575aca
