### ISSUE TITLE
Balão de dicas com visualização fraca

### ISSUE THREAD

**Issue by mnt-c** [IBICT/noosfero#65]
Encontrado na criação de novo usuário em mais de 2 temas, onde quando focado um campo a dica num formato de balão é chamada, porém com uma visualização não muito amigavel.

![screenshot from 2018-03-08 14-06-34](https://user-images.githubusercontent.com/18350825/37171268-0fa5cf6e-22ec-11e8-9702-a37d6d23e90e.png)

**Comment by maxbborges** [comment]
Aguardando aceitação do merge
Link https://gitlab.com/noosfero/noosfero/merge_requests/1419

As modificações efetuadas foram:
https://gitlab.com/noosfero/noosfero/commit/7dee4b925e3b4f6dcb73ada77f4eb7fa16af420c

**Comment by maxbborges** [comment]
Merge aceito!
