### ISSUE TITLE
Páginas carregando desconfiguradas

### ISSUE THREAD

**Issue by estelanm** [IBICT/noosfero#66]
As vezes, as páginas carregam fora de configuração...
![whatsapp image 2018-03-12 at 11 25 58](https://user-images.githubusercontent.com/34688898/37347081-ce669fca-26af-11e8-9fa4-c7c419c466e4.jpeg)
![whatsapp image 2018-03-12 at 11 27 30](https://user-images.githubusercontent.com/34688898/37347083-ce948980-26af-11e8-8d19-96d30974ed47.jpeg)

**Comment by FabioDsg** [comment]
Bom dia, Estela!
O problema ainda persiste? 
Acabei de realizar um teste na página acima e abriu normalmente, inclusive utilizando o navegador firefox.

**Comment by estelanm** [comment]
É um problema que vai e volta... como quase todos apresentados! hahaha
