### ISSUE TITLE
Um usuário relatou problemas nestas páginas

### ISSUE THREAD

**Issue by estelanm** [IBICT/noosfero#67]
Não sei que tipo de problema, porém acredito que é instabilidade do servidor mesmo

Páginas com problemas no site juventude – Estação Juventude
Links (editais e documentos) da página http://juventude.gov.br/estacaojuventude/edital-12017#.Wqfe6Grwbb1

http://juventude.gov.br/estacaojuventude/arquivos/e-book-a-5-caderno-juventude.pdf
http://www.juventude.gov.br/estacao-juventude-gestores/modelos/modelos
http://juventude.gov.br/estacaojuventude/arquivos/e-book-guia-juventude.pdf

E página 2 dos programas para a Juventude:

http://juventude.gov.br/juventude/programas
http://juventude.gov.br/juventude/programas?npage=2

**Comment by FabioDsg** [comment]
Estamos verificando.

**Comment by FabioDsg** [comment]
@estelanm Está sendo realizada uma manutenção e temporariamente a navegação no portal será afetada causando esses erros.
