### ISSUE TITLE
avaliar e testar usabilidade do plugin custom_forms

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#7]
fazer o setup local do noosfero, colocar o plugin pra funcionar, testar a usabilidade, verificar se atende para formulários simples que são demandas comuns da secretaria

**Comment by joenio** [comment]
este plugin está junto ao repositório oficial do noosfero:

* https://gitlab.com/noosfero/noosfero/tree/master/plugins/custom_forms

**Comment by joenio** [comment]
este plugin está junto ao repositório oficial do noosfero:

* https://gitlab.com/noosfero/noosfero/tree/master/plugins/custom_forms

para entender melhor a arquitetura dos plugins no noosfero:

* http://noosfero.org/bin/view/Development/Plugins

**Comment by joenio** [comment]
este plugin está junto ao repositório oficial do noosfero:

* https://gitlab.com/noosfero/noosfero/tree/master/plugins/custom_forms

para entender melhor a arquitetura dos plugins no noosfero:

* http://noosfero.org/bin/view/Development/Plugins

**Comment by joenio** [comment]
este plugin está junto ao repositório oficial do noosfero:

* https://gitlab.com/noosfero/noosfero/tree/master/plugins/custom_forms

para entender melhor a arquitetura dos plugins no noosfero:

* http://noosfero.org/bin/view/Development/Plugins

**Comment by mnt-c** [comment]
Consegui utilizar o custom forms

![desktop 1_045](https://user-images.githubusercontent.com/18350825/32740128-12a51a16-c889-11e7-9da5-66df726df58e.png)

**Comment by mnt-c** [comment]
Ele requer um campo de para inserir usuário e email (pode ser uma qualquer) por default, caso não esteja com uma conta logada.

Não possui upload de arquivos somente tem campos para inserção de texto e de seleção de dados pré definidos.

**Comment by mnt-c** [comment]
Ele gera um relatório de respostas e gera um arquivo .CSV, porém quando é aberto o caminho com o .CSV é gerado um erro na tela: 

![desktop 1_044](https://user-images.githubusercontent.com/18350825/32740427-111512ea-c88a-11e7-901e-5e9c1ca003cc.png)

Erro gerado ao acessar o CSV:

![desktop 1_043](https://user-images.githubusercontent.com/18350825/32740440-1c055a70-c88a-11e7-8ad0-df400520b7e7.png)

**Comment by joenio** [comment]
estou fechando esta issue já que criamos duas novas issues com a avaliação feita aqui.
