### ISSUE TITLE
validar se o paperclip funciona bem com imagens svg

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#70]

**Comment by luucilia** [comment]
Eu testei o paperclip e ele funciona bem com imagens svg e com a parte de criar thumbnails. Eu coloquei no meu git um programa simples que faz upload de imagens e gera as thumbnails, segue o link: https://github.com/luciliapo/uploader_paperclip.

No entanto, eu fiz uma pesquisa e vários sites não recomendam o uso do paperclip quando se trata de aplicações complexas com vários uploads, processamento de imagens e gerenciamento de cache. 

Acredito que outras alternativas que ofereçam melhores resultados podiam ser avaliadas e uma alternativa poderia ser o Carrierwave que, a princípio, possui uma boa review na internet.

**Comment by joenio** [comment]
legal @luciliapo bom trabalho!

parece mesmo que o paperclip sofre uma série de problemas, dei uma lida bem rápida em alguns blogs e notei que ele não parece ser mesmo a melhor opção, fiquei em dúvida sobre uma outra alternativa, um projeto chamado Shrine, me parece uma boa alternativa, você pode avaliar ele em comparação com o CarrierWave para termos uma idéia de qual seria mais indicado?

link para repositórios de projetos para tratar upload/arquivos em Ruby:

* https://github.com/technoweenie/attachment_fu
* https://github.com/carrierwaveuploader/carrierwave
* https://github.com/refile/refile
* https://github.com/shrinerb/shrine
* https://github.com/thoughtbot/paperclip

**Comment by luucilia** [comment]
Eu testei o CarrierWave e as funções básicas como upload de uma única imagem e gerar thumbnails para vários formatos de imagens funcionam, além disso testei com a funcionalidade de upload de múltiplas imagens e funcionou também. Salvei no meu git: https://github.com/luciliapo/uploader_carrierwave

A documentação é bem clara e concisa e tem várias outras funcionalidades como ajustar a imagem, fazer upload via URL, armazenar na cloud, permite migrar os dados do paperclip pra ele, entre outras que eu não testei por motivos de simplificação e, aparentemente, ele é atualizado com frequência já que o último commit foi mês passado.

Testarei agora o Shrine.

**Comment by luucilia** [comment]
Eu testei o Shrine e o desempenho  e as funcionalidades superficialmente falando são semelhantes ao CarrierWave. O criador do Shrine aponta que a forma como lida com as imagens em background é mais eficiente que o CarrierWave. Um simples protótipo pode ser encontrado em: https://github.com/luciliapo/uploader_shrine

No meu ponto de vista, o Shrine parece ter um grande potencial. Minha preocupação é que, pelo Shrine ser relativamente novo, não possui muito material na internet e talvez isso seja um obstáculo para implementá-lo no Noosfero. Minha sugestão é que se utilize o CarrierWave devido ao seu suporte e estabilidade para lidar com imagens.
