### ISSUE TITLE
criar protótipo de tela para compartilhamento com meteor

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#71]
criar tela simulando a interface de edição de artigos do noosfero com novo campo, botão ou link para gerar token e link para compartilhamento.

**Comment by mnt-c** [comment]
Havia criado com o meteor uma tela muito simples  com o objetivo a ideia para funcionalidade. 

![screenshot from 2018-04-06 13-30-37](https://user-images.githubusercontent.com/18350825/38434764-e8ee092e-39a5-11e8-9e17-aa08f87864f8.png)


Inicialmente pensou em deixar os icones mais proximos numa aba lateral, ou uma forma que fosse mais facil navegar nos items e diminuir a barra de rolagem, segmentando os campos:
Uma area para inserir/editar dados padrão como titulo, conteudo,local;
Uma area para dados mais especificos;
Uma area para quesitos de privacidade;
E uma area para compartilhar a postagem.

O compartilhamento da postagem teria um botão/link da postagem que através dele voce conseguiria acessar aquela post em especifico para visualização em ambiente fechado.

**Comment by mnt-c** [comment]
No ambiente responsivo do Noosfero e no tema do angular, tem uma interface mais interativa de dados. Vou testar um novo modelo do meteor com base em um desses temas.

**Comment by mnt-c** [comment]
Na nova modelagem com meteor, fiz um teste que poderia ser proximo da funcionalidade para o usuário. Fui tendo como uma visão o tema responsivo. E ideia que foi pensada foi a seguinte:

1. O usuário teria em uma das opções de uma publicação, algo como um botão de compartilhamento;
2. Apareceria algo como um frame com a tela de compartilhamento;
3. Nessa tela ele iria poder gerar um link para compartilhamento;
4. O link poderia ter acesso permanente ou um tempo de expiração;
5. Caso não houvesse mais interesse de ter esse link ativo o mesmo poderia ser desativado.

![screenshot from 2018-04-12 16-14-09](https://user-images.githubusercontent.com/18350825/38699053-5ac78f9a-3e6d-11e8-9d9f-ffec5efad2f4.png)

![compart](https://user-images.githubusercontent.com/18350825/38699001-38e6d03e-3e6d-11e8-96d1-2f5205102147.gif)

Também foi sugerido que já tinha uma funcionalidade "Divulgar" nas ações de uma publicação e poderia incorporar essa funcionalidade dentro desse local.

Fiz então uma adaptação mais simples só para verificar como poderia ficar dentro de divulgar visualmente.

![screenshot from 2018-04-12 16-02-58](https://user-images.githubusercontent.com/18350825/38698728-6c87a5b8-3e6c-11e8-8a7b-b88736f6071a.png)
