### ISSUE TITLE
rodar localmente e estudar o noosfero-responsivo

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#72]
validar o quão maduro está o noosfero-responsivo e avaliar se é viável a adoção dele para o novo tema do juventude.gov.br.

**Comment by FabioDsg** [comment]
Foi verificado que as implementações relacionadas a responsividade, foram realizadas diretamente no código do Noosfero. Em um primeiro momento parece não atender a proposta, uma vez que o intuito inicial seria não realizar alterações diretamente no código fonte.

**Comment by joenio** [comment]
@FabioDsg não entendi muito bem porque não atende, o que significa "intuito inicial seria não realizar alterações diretamente no código fonte" ?

**Comment by FabioDsg** [comment]
Percebo que houve um equívoco da minha parte. Estarei buscando entender melhor e reavaliando.
