### ISSUE TITLE
entrar em contato com o design do ibict e solicitar o protótipo do novo tema

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#73]
avaliar se o design proposto pelo ibict encaixa no noosfero-responsivo e iniciar implementação em código no noosfero.

**Comment by FabioDsg** [comment]
O design estará atuando no tema novo assim que o portal estiver atualizado e homologado.
No momento  não é possível a disponibilização de um protótipo.

**Comment by joenio** [comment]
@FabioDsg lembro que o ibict já tinha contratado alguém para desenhar uma proposta de layout, nós precisamos ter acesso a essa proposta, você entrou em contato com quem no ibict sobre isso?

**Comment by FabioDsg** [comment]
Falei diretamente com Milton, a informação obtida foi que, devido a existência de outras demandas, o design ainda não deu início a esta. O trabalho no tema será iniciado assim que  uma versão atualizada e estável do portal estiver rodando. 

Assim não há um protótipo disponível no momento.

**Comment by joenio** [comment]
ok, fechando a issue por hora então, @FabioDsg você pode pedir ao milton nos avisar quando o design começar a ser elaborado? valeu!
