### ISSUE TITLE
entender os conceitos do active record e suas relações

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#76]
ler com atenção e realizar os exercícios práticos propostos no documento abaixo:

* http://guides.rubyonrails.org/association_basics.html

**Comment by joenio** [comment]
@caiomnt @maxbborges @FabioDsg @luciliapo vocês fizeram esse "dever de casa" já?

**Comment by FabioDsg** [comment]
A parte teórica está em andamento. Os exercícios ainda não.

**Comment by maxbborges** [comment]
Eu só fiz uma leitura superficial de algumas funcionalidades, hj que vou testar e entender o funcionamento.
