### ISSUE TITLE
Erro ao colocar novo destaque no carrossel da página inicial

### ISSUE THREAD

**Issue by estelanm** [IBICT/noosfero#77]
![image](https://user-images.githubusercontent.com/34688898/37616732-9e27a77a-2b8f-11e8-9769-4dd24a1f0272.png)

**Comment by luucilia** [comment]
@estelanm, a intenção é adicionar uma nova imagem no carrossel de imagens ou um novo banner além daqueles 3 que têm no site atualmente?

**Comment by luucilia** [comment]
Essa issue foi resolvida.
