### ISSUE TITLE
Retirar faixa preta de título no banner do carrossel

### ISSUE THREAD

**Issue by estelanm** [IBICT/noosfero#78]
Pessoal, como nossos banners que vão para o carrossel na página principal já vem com título, optamos por retirar a opção de título que o noosfero oferece. Acontece que, qnd retiramos o título, uma faixa preta permanece, como na figura abaixo. Lembrando que não é td banner que vai sem título, então a opção de titular o banner tem q continuar existindo, porém a faixa preta deve desaparecer, caso o usuário opte por não titular. Segue imagem:

![image](https://user-images.githubusercontent.com/34688898/37973137-39312da6-31b0-11e8-918a-7335adefbaf9.png)

**Comment by maxbborges** [comment]
O banner 11, do novo juventude viva, estava com título. Esse titulo teve o texto centralizado para uma melhor apresentação. Mas caso não tenha gostado podemos retirar também:
![captura de tela de 2018-03-27 13-24-57](https://user-images.githubusercontent.com/18174772/37980808-6a88cf28-31c2-11e8-9fc7-02d920d49f7b.png)

Para os outros banners, sem titulo, foi retirado a tarja:
![captura de tela de 2018-03-27 13-25-14](https://user-images.githubusercontent.com/18174772/37980875-8db90fc6-31c2-11e8-8d90-0dcbb6ad762d.png)

Para correção do problema foi inserido o seguinte código CSS no bloco de HTML puro:
``` CSS
.highlights-label {
padding: 0px;
text-align: center;
}
```

**Comment by luucilia** [comment]
Issue resolvida.
