### ISSUE TITLE
Substituir video na página inicial

### ISSUE THREAD

**Issue by estelanm** [IBICT/noosfero#79]
Tentei substituir o video da página inicial e tenho o acesso negado após salvar a edição.
O  novo vídeo está neste link: https://youtu.be/ZahN05JoaH0
![image](https://user-images.githubusercontent.com/34688898/38211621-70bfcd1e-3691-11e8-8a39-9fae62a75a12.png)

**Comment by mnt-c** [comment]
Consegui reproduzir o problemas, quando um bloco de vídeo é inserido/editado ele aparece algumas opções, conforme a imagem abaixo:

![image](https://user-images.githubusercontent.com/18350825/38266986-76a5c23c-3750-11e8-9a14-31e80e79662b.png)

Na parte que possui **Opções de edição**, possui um problema quando é escolhido **Não pode ser Modificada**. Ele não permite edição do conteúdo mesmo como conta adminstrativa, porém só ocorre quando é selecionado essa opção e o bloco salvo. 

Removi o bloco antigo e recriei o bloco com a permissão de modificação.

Está funcional agora, mas vamos verificar se ocorre nas versões mais novas da ferramenta também e caso positivo vamos abrir uma nova issue para corrigi-lo.
