### ISSUE TITLE
implementar testes e fazer merge-request corrigindo bloco CustomForms no Environment

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#80]
relacionada a issue #64

**Comment by maxbborges** [comment]
Aguardando aprovação do merge:
https://gitlab.com/maxbborges/noosfero/commit/84878116685b50ca75ef51f8bd719b3d79575aca

**Comment by maxbborges** [comment]
Merge aceito:
https://gitlab.com/noosfero/noosfero/merge_requests/1436#note_69358437
