### ISSUE TITLE
Criar Comunidade "Conselhos em Rede"

### ISSUE THREAD

**Issue by estelanm** [IBICT/noosfero#82]
Precisamos criar esta comunidade e, na página inicial dela, embedar um Formulário do Google. Lembrem de deixar um espaço acima pra que eu possa adicionar um parágrafo.

Segue link do form: https://docs.google.com/forms/d/e/1FAIpQLSdMeRqxsxqln9QyizjaAW-EIPR1KBSQ00aY8ednLsUcFfyujQ/viewform?usp=sf_link

(não tem codigo de incorporação pq o form tem upload de arquivos, alguma solução pra isto?)

Segue logo para o avatar: 
![encontro_coselhos_vf_a](https://user-images.githubusercontent.com/34688898/38705991-ef662828-3e81-11e8-8ba0-004828024cf0.png)

**Comment by joenio** [comment]
**opção 1** adicionar o código abaixo num artigo da comunidade, editando o html dele:

```html
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdMeRqxsxqln9QyizjaAW-EIPR1KBSQ00aY8ednLsUcFfyujQ/viewform" width="720" height="500"></iframe>
```

veja exemplo em: http://juventude.gov.br/joenio/survey-teste

apesar de funcionar, essa solução tem o iconveniente de exibir um botão pedindo login ao usuário.

ps.: o mesmo pode ser feito com um bloco HTML.

**Comment by joenio** [comment]
**opção 2** adicionar o código abaixo num bloco html puro (o firewall me bloqueou):

```html
<script>
$( function() {
  $( "#mapa-dialog" ).dialog();
});
</script>

<div id="mapa-dialog" title="Mapeamento Conselhos de Juventude do Brasil" style="display:none">
  <p>
    Responda ao <a href="https://docs.google.com/forms/d/e/1FAIpQLSdMeRqxsxqln9QyizjaAW-EIPR1KBSQ00aY8ednLsUcFfyujQ/viewform?usp=sf_link">Mapeamento Conselhos de Juventude do Brasil</a> ... (texto convidando usuário a participar aqui).
  </p>
</div>
```

veja exemplo em: http://softwarelivre.org/joenio?lang=eo

essa solução tem o inconveniente de exibir o "popup" em todas as páginas da comunidade.

**Comment by FabioDsg** [comment]
Segue o link da comunidade criada conforme solicitado. Foi utilizado o código sugerido pelo @joenio na primeira opção. 

http://juventude.gov.br/conselhos-em-rede/blog#.WtCbWYDQ-Cg

Foi sugerido também verificar as opções de configurações no Google Forms afim de remover a possível restrição que esteja causando esse pop-up solicitando login.

**Comment by estelanm** [comment]
Criar ícone da comunidade na pagina inicial 
![image](https://user-images.githubusercontent.com/34688898/38740299-9b583a00-3f0d-11e8-9494-4cd82d80ea94.png)

**Comment by FabioDsg** [comment]
@estelanm Usar a mesma imagem do perfil da comunidade?

**Comment by estelanm** [comment]
Isso! ^^ precisa ser em outra dimensão?

**Comment by estelanm** [comment]
Pessoal, a página inicial deste comunidade deve ser a que está com o formulário publicado. No momento, a que aparece quando clicamos no novo ícone criado é esta:

![image](https://user-images.githubusercontent.com/34688898/38749571-6c7151f2-3f28-11e8-8fde-2a90b2fdb487.png)

**Comment by estelanm** [comment]
Nesta imagem de cabeçalho, preciso incluir o link para o formulário, porém não consigo incluir da maneira convencional. Vcs podem fazer isso no html? link: https://goo.gl/forms/B3v6Xe5MV9lZAm0V2

![image](https://user-images.githubusercontent.com/34688898/38751308-08f4865c-3f2e-11e8-94ac-694756d141dd.png)

**Comment by mnt-c** [comment]
A imagem ela em geral é auto redimensionada para não fugir um bloco, então precisa se preocupar tanto caso ela seja muito grande. ;)

Para definir uma pagina/blog/outros como página inicial o processo é simples:

No painel de controle acessamos a parte de "Gerenciar Conteúdo" e podemos escolher o que deverá ser a página inicial:

![image](https://user-images.githubusercontent.com/18350825/38752965-49b7f2b4-3f33-11e8-8cca-e6fb3799eb89.png)

Fiz a alteração para ser somente a postagem que está dentro do Blog, para ser o campo do formulário e inclui tambem o link no banner, onde que fiz pelo html mesmo botando uma tag de href:

```HTML
<a href="https://goo.gl/forms/B3v6Xe5MV9lZAm0V2">
<img> ... </img>
</a>
```

**Comment by luucilia** [comment]
Comunidade, ícone e formulários criados.
