### ISSUE TITLE
consulta pública na comunidade Plano Nacional de Juventude

### ISSUE THREAD

**Issue by estelanm** [IBICT/noosfero#83]
Ano passado , fizemos uma consulta pública na comunidade Plano Nacional de Juventude
Ela ficou disponível de novembro a janeiro deste ano
Precismos resgatar esta página para uma filmagem
O Joenio que desenvolveu a página na época, ele deve ter o caminho mais fácil pra isso

**Comment by luucilia** [comment]
A página da Consulta Pública foi liberada para acesso ao público e pode ser acessada pelo link: http://juventude.gov.br/plano-nacional-de-juventude/blog/consulta-publica-online-contribua-com-o-plano-nacional-de-juventude
