### ISSUE TITLE
Criar botão de download para arquivo PDF

### ISSUE THREAD

**Issue by FabioDsg** [IBICT/noosfero#95]
Foi solicitado a criação de um botão de download na comunidade Plano Nacional de Start Ups no intuito de disponibilizar um documento no formato PDF para download.

**Comment by estelanm** [comment]
em anexo, o arquivo para PDF que ficará no botão "Baixe o Plano Nacional de Empreendedorismo e StartUp para a Juventude"

Plano Nacional de Startups_VISUALIZAÇÃO_.pdf

**Comment by estelanm** [comment]
[Plano Nacional de Startups_VISUALIZAÇÃO_.pdf](https://github.com/IBICT/noosfero/files/2167670/Plano.Nacional.de.Startups_VISUALIZACAO_.pdf)

**Comment by estelanm** [comment]
Arquivo anterior com erros. Segue o correto:

[Plano Nacional de Startups_VISUALIZAÇÃO(1).pdf](https://github.com/IBICT/noosfero/files/2168086/Plano.Nacional.de.Startups_VISUALIZACAO.1.pdf)

**Comment by luucilia** [comment]
O firewall bloqueia a opção de colocar um botão, então eu coloquei de forma simplificada a opção de fazer o download do PDF, conforme a imagem mostra:

![screen shot 2018-07-06 at 1 00 37 pm](https://user-images.githubusercontent.com/17516861/42388734-df3b2024-811c-11e8-88b4-186f43f2b8a9.png)

**Comment by estelanm** [comment]
A ideia era colocar um botão no menu lateral. 
Vc consegue colocar, no menu lateral, um hipertexto "Baixe aqui o Plano Nacional de Empreendedorismo e StartUp para a Juventude"?

Temos uma nova versão do arquivo, que precisa ser substituída. Segue:

[Plano Nacional de Startups_VISUALIZAÇÃO_ (1).pdf](https://github.com/IBICT/noosfero/files/2176741/Plano.Nacional.de.Startups_VISUALIZACAO_.1.pdf)

**Comment by estelanm** [comment]
[Plano Nacional de Startups_VISUALIZAÇÃO_.pdf](https://github.com/IBICT/noosfero/files/2189568/Plano.Nacional.de.Startups_VISUALIZACAO_.pdf)


NOVA VERSÃO DO ARQUIVO

**Comment by FabioDsg** [comment]
A alteração foi realizada.

**Comment by estelanm** [comment]
Pode fechar a issue @FabioDsg
