### ISSUE TITLE
Alterações no Portal - adequações ao período eleitoral

### ISSUE THREAD

**Issue by estelanm** [IBICT/noosfero#97]
Boa tarde,
Seguem as alterações:

![whatsapp image 2018-07-05 at 15 14 01](https://user-images.githubusercontent.com/34688898/42341830-c0efcb04-806a-11e8-9397-2d168963d096.jpeg)
Substituir banner superior por esta imagem:

![whatsapp image 2018-07-05 at 15 15 18](https://user-images.githubusercontent.com/34688898/42341853-d2837758-806a-11e8-8707-1b87aceac7eb.jpeg)

![whatsapp image 2018-07-05 at 15 14 15](https://user-images.githubusercontent.com/34688898/42341861-d9fc699a-806a-11e8-9185-77197d89f617.jpeg)
Excluir logo do Governo do Brasil

![whatsapp image 2018-07-05 at 15 16 53](https://user-images.githubusercontent.com/34688898/42341872-e5f387ec-806a-11e8-9a1e-dae4644fe8cd.jpeg)
Remover botões e reposicionar o do ID Jovem

**Comment by estelanm** [comment]
![whatsapp image 2018-07-05 at 15 14 09](https://user-images.githubusercontent.com/34688898/42342234-edf85b6a-806b-11e8-8549-05203a8322a5.jpeg)

substituir os botões por estas imagens a seguir

![whatsapp image 2018-07-05 at 15 55 28 1](https://user-images.githubusercontent.com/34688898/42342713-480c121c-806d-11e8-8ce0-cfb01281e19d.jpeg)
![whatsapp image 2018-07-05 at 15 55 28](https://user-images.githubusercontent.com/34688898/42342714-4831ba80-806d-11e8-9312-331bab00c134.jpeg)
![whatsapp image 2018-07-05 at 15 55 29 1](https://user-images.githubusercontent.com/34688898/42342715-4855c8b2-806d-11e8-9327-011ff0391504.jpeg)
![whatsapp image 2018-07-05 at 15 55 29 2](https://user-images.githubusercontent.com/34688898/42342717-48768e4e-806d-11e8-8677-a2e745f3a26f.jpeg)
![whatsapp image 2018-07-05 at 15 55 29 3](https://user-images.githubusercontent.com/34688898/42342718-4896c574-806d-11e8-8a5f-abe710a8b832.jpeg)
![whatsapp image 2018-07-05 at 15 55 29](https://user-images.githubusercontent.com/34688898/42342720-48c1db74-806d-11e8-9956-3347a09df5fa.jpeg)
![whatsapp image 2018-07-05 at 15 55 30 1](https://user-images.githubusercontent.com/34688898/42342721-48faa6a2-806d-11e8-8b0e-86c98aa03297.jpeg)
![whatsapp image 2018-07-05 at 15 55 30 2](https://user-images.githubusercontent.com/34688898/42342723-491a7310-806d-11e8-9169-7fd2f408c4a3.jpeg)
![whatsapp image 2018-07-05 at 15 55 30 3](https://user-images.githubusercontent.com/34688898/42342724-49397382-806d-11e8-87a2-0b5a31cecaa9.jpeg)
![whatsapp image 2018-07-05 at 15 55 30 4](https://user-images.githubusercontent.com/34688898/42342725-495f3c98-806d-11e8-931e-25101dbcf6b7.jpeg)
![whatsapp image 2018-07-05 at 15 55 30 5](https://user-images.githubusercontent.com/34688898/42342726-4980264c-806d-11e8-91fb-38b01435112b.jpeg)
![whatsapp image 2018-07-05 at 15 55 30 6](https://user-images.githubusercontent.com/34688898/42342727-49a4a968-806d-11e8-850f-de051de05628.jpeg)
![whatsapp image 2018-07-05 at 15 55 30](https://user-images.githubusercontent.com/34688898/42342728-49c4c388-806d-11e8-88ca-b842c0d467b2.jpeg)
![whatsapp image 2018-07-05 at 15 55 31 1](https://user-images.githubusercontent.com/34688898/42342729-49ed17ac-806d-11e8-8310-9078106dc4f2.jpeg)
![whatsapp image 2018-07-05 at 15 55 31 2](https://user-images.githubusercontent.com/34688898/42342730-4a0c43a2-806d-11e8-8361-ec3d4275d599.jpeg)
![whatsapp image 2018-07-05 at 15 55 31 3](https://user-images.githubusercontent.com/34688898/42342731-4a2bdd02-806d-11e8-9af3-67dc76a062f0.jpeg)
![whatsapp image 2018-07-05 at 15 55 31 4](https://user-images.githubusercontent.com/34688898/42342732-4a4d4bf4-806d-11e8-8e7c-81f1f5dcbe54.jpeg)
![whatsapp image 2018-07-05 at 15 55 31](https://user-images.githubusercontent.com/34688898/42342734-4a726ce0-806d-11e8-80a2-dddf3b2b7ed4.jpeg)

**Comment by estelanm** [comment]
banner anterior estava errado, segue banner com ajustes

![whatsapp image 2018-07-05 at 16 54 43](https://user-images.githubusercontent.com/34688898/42344936-3a10e334-8074-11e8-9713-0ae918fe038f.jpeg)

**Comment by FabioDsg** [comment]
As modificações iniciais foram realizadas conforme o solicitado.

@estelanm Estou com uma dúvida em relação ao banner, a idéia seria a subtituição do banner todo ou apenas essa logo? 

<img width="212" alt="old_logo" src="https://user-images.githubusercontent.com/8026759/42386418-d12cf3ec-8115-11e8-9f0f-09a3529fa973.PNG">

De qualquer forma, a logo faz parte do background que teria que ser substituído por completo.

**Comment by estelanm** [comment]
Novo banner com dimensões corretas HEADER

![cover_portal_snj_periodo_eleitoral_b](https://user-images.githubusercontent.com/34688898/42459062-74e38fd4-8371-11e8-9417-35b3d36a46fc.jpg)

**Comment by estelanm** [comment]
Imagem para colocar no FOOTER, no lugar do logo do Governo do Brasil.
Essa img tem fundo transparente

![whatsapp image 2018-07-09 at 12 21 15](https://user-images.githubusercontent.com/34688898/42459735-afeea6a8-8372-11e8-8c8f-f71027ac88b8.jpeg)

**Comment by estelanm** [comment]
Retificando: podem apenas retirar o logo do governo do brasil do footer e deixar sem nada

**Comment by maxbborges** [comment]
Foi alterado o FOOTER, retirando o logotipo, como solicitado. Quanto ao HEADER, para modificação da imagem é necessário permissão de modificação, foi solicitado essa permissão e estamos aguardando a aceitação para que possa ser realizado a modificação.

**Comment by estelanm** [comment]
![whatsapp image 2018-07-05 at 15 55 29 5](https://user-images.githubusercontent.com/34688898/42469653-bba19ef8-838e-11e8-9dde-b2bc88287ba5.jpeg)
![whatsapp image 2018-07-09 at 15 41 32](https://user-images.githubusercontent.com/34688898/42469655-bbc63a06-838e-11e8-8cc2-6f924fdd6b4a.jpeg)
![whatsapp image 2018-07-09 at 15 40 12](https://user-images.githubusercontent.com/34688898/42469656-bbe6dce8-838e-11e8-8e40-58d4f78fd01a.jpeg)

**Comment by maxbborges** [comment]
Todas as alterações foram realizadas.
Caso esteja de acordo, favor fechar a issue.

**Comment by estelanm** [comment]
banner do header só aparece na página inicial. Verificar porque não aparece nas comunidades e notícias...

**Comment by maxbborges** [comment]
Para solução do problema, será necessário abrir uma OS em Portal/Juventude/Manutenção, em anexo é necessário colocar o novo banner com tamanho de 1735x150 e nome bg-juventude.jpg.

**Comment by estelanm** [comment]
Alinhar o tamanho das imagens no bloco central de programas....

**Comment by FabioDsg** [comment]
O tamanho das imagens foi alinhado.

**Comment by estelanm** [comment]
O banner nas páginas de navegação, comunidades e etc. continua o antigo. Abri a OS e enviei a img pro email da Nayanne

**Comment by joenio** [comment]
alteramos a imagem para se adequar ao layout, estamos alterando neste momento nos servidores de produção.

![bg-juventude](https://user-images.githubusercontent.com/44172/42823135-3284b864-89b3-11e8-9b22-14dae5b73a7d.jpg)

**Comment by joenio** [comment]
oi @estelanm, a alteração do banner foi feita.
